-- =====================================================================
-- 016 — Supervisores (com código) e Representantes/RCA
-- ---------------------------------------------------------------------
-- Fontes (18/08/2026): REPRESENTANTES.xlsx (258 RCAs, arquivo oficial) e
-- a lista de supervisores com código enviada em imagem pela operação.
-- ATENÇÃO: os supervisores foram transcritos de IMAGEM — os códigos devem
-- ser conferidos pela Logística; um errado se corrige cadastrando o certo
-- pela tela (o formato é livre) e avisando para remover o incorreto.
-- =====================================================================

CREATE TABLE IF NOT EXISTS dim_representantes (
    nome      TEXT PRIMARY KEY,
    criado_em TIMESTAMPTZ NOT NULL DEFAULT now()
);

INSERT INTO dim_supervisores (nome) VALUES ('101781 - Manoel Antonio Lopes Rego') ON CONFLICT DO NOTHING;
INSERT INTO dim_supervisores (nome) VALUES ('102536 - Maurecy Rodrigues Araujo') ON CONFLICT DO NOTHING;
INSERT INTO dim_supervisores (nome) VALUES ('98342 - Fabio Athayde dos Santos') ON CONFLICT DO NOTHING;
INSERT INTO dim_supervisores (nome) VALUES ('88906 - Rayane Galvao do Couto') ON CONFLICT DO NOTHING;
INSERT INTO dim_supervisores (nome) VALUES ('86040 - Bruno Cesar Gomes e Silva') ON CONFLICT DO NOTHING;
INSERT INTO dim_supervisores (nome) VALUES ('98745 - Renato de Oliveira Machado') ON CONFLICT DO NOTHING;
INSERT INTO dim_supervisores (nome) VALUES ('101454 - Makson Werlly Lopo da Silva') ON CONFLICT DO NOTHING;
INSERT INTO dim_supervisores (nome) VALUES ('101484 - Lucas Cotta Dias Oliveira') ON CONFLICT DO NOTHING;
INSERT INTO dim_supervisores (nome) VALUES ('102691 - Raquel Souza Guimaraes Pantuzzo') ON CONFLICT DO NOTHING;
INSERT INTO dim_supervisores (nome) VALUES ('103598 - Marcos Henrique de Melo') ON CONFLICT DO NOTHING;
INSERT INTO dim_supervisores (nome) VALUES ('98125 - Weber Vaz de Melo Junior') ON CONFLICT DO NOTHING;
INSERT INTO dim_supervisores (nome) VALUES ('86692 - Thiago Goncalves da Silva') ON CONFLICT DO NOTHING;
INSERT INTO dim_supervisores (nome) VALUES ('102192 - Kennedy Camilo Costa') ON CONFLICT DO NOTHING;
INSERT INTO dim_supervisores (nome) VALUES ('98036 - Thiago de Mendonca Gomes') ON CONFLICT DO NOTHING;
INSERT INTO dim_supervisores (nome) VALUES ('88945 - Cristiano Dornellas Pinto') ON CONFLICT DO NOTHING;
INSERT INTO dim_supervisores (nome) VALUES ('88570 - Debora Cristina Silva') ON CONFLICT DO NOTHING;
INSERT INTO dim_supervisores (nome) VALUES ('100026 - Claudio Martins Coelho') ON CONFLICT DO NOTHING;
INSERT INTO dim_supervisores (nome) VALUES ('38942 - Fabio Athayde dos Santos') ON CONFLICT DO NOTHING;

INSERT INTO dim_representantes (nome) VALUES ('80031 - L Marinho Representacao Comercial Eireli (Bahia)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('80065 - F & D Representacoes Ltda - ME (Alto Paranaiba)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('80133 - Alesmag Representacoes Ltda ME (RJ Capital)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('80137 - Integra Representacoes Ltda - ME (CENTRO OESTE)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('80184 - Ramon Frederick Gontijo Silveira - ME (Norte de Minas)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('80191 - L.AD Representacoes Ltda ME (Alto Paranaiba)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('80193 - A&D Representacoes Ltda - ME (Alto Paranaiba)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('80209 - Manuel Balduino Gomes de Freitas (Triangulo Mineiro)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('80235 - Carlos Eduardo de Conti (SP Interior)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('80256 - Rep Cenecarnes Central de Negocios de Carne (SP Capital)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('80273 - Comercio e Representacoes de Prod. Alim. Otoni (Goias)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('80385 - Diemerson Aparecido Goncalves - ME (Triangulo Mineiro)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('80398 - Reinaldo Antonio Variz da Costa (Zona da Mata)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('80422 - Regal Representações Comerciais Ltda-Me (Triangulo Mineiro)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('80452 - Rodrigues e Bertolino Representacoes Ltda - Me (Alto P.)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('80460 - Josemar Bezerra Representacoes Ltda ME (RJ Capital)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('80461 - Vitoria Come e Representacao de Frios e Cong. (RJ Interior)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('80487 - Milton Pereira Silva 93556217600 (BH)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('80506 - Lomeu Representacoes Ltda - Me (RJ Capital)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('80510 - Everton Vital de Rezende - Me  (Zona da Mata)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('80511 - Paulo Roberto Ferreira Braz (RJ Capital)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('80525 - Eduardo AP de Jesus (Rj Capital)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('80535 - Marco Antonio de Oliveira Goncalves (RJ Capital)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('80540 - JPT Representacoes Eireli - Me (SP Interior)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('80541 - Vilmar de Melo CPF 71164227653 - Me (Alto Paranaiba)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('80546 - Ivair Jose Pereira (RJ Interior)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('80550 - R e B Representações Comerciais Ltda - Me (DF)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('80553 - C. Correa de Mello e Cia Ltda - Me (SP Interior)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('80554 - S. Medina (SP Interior)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('80557 - Vilson Cesar da Silva - Me (Triangulo Mineiro)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('80558 - BS Rio Representacoes Ltda ME (RJ Interior)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('80561 - ANL de Oliveira - Representacoes - Me (DF)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('80565 - RJ Representacoes Comerciais Ltda (RJ Interior)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('80581 - Daniela Christina Silva Grossi') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('80587 - Vanderli Ferreira da Silva CPF 008.625.406-58 (Alto P.)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('80600 - BRP Promocao de Vendas Eireli - Me (SP Interior)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('80601 - Rafael Silva Representações - Me (Alto Paranaiba)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('80609 - Barreto e Medeiros Representacoes Ltda - Me (DF)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('80610 - Jose Augusto Cardoso Lopes 0618428698 - Me (CENTRO OESTE)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('80612 - Tervic Representacoes de Generos Alimenticios (SP Capital)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('80613 - P J Santana Representacao Comercial Ltda Me (SP Capital)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('80615 - Broker Costa Norte Distribuicao Ltda (SP Capital)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('80632 - Barbara Representacoes Eireli - Me (BH)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('80638 - E.P. de Oliveira Representacoes - Me (SP Interior)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('80649 - Jose Nilton Correia de Lira (DF)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('80655 - Reobote Representacoes Ltda - Me (RJ Capital)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('80656 - Renato dos Santos Eireli (Triangulo Mineiro)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('80666 - Rosilene Goncalves da Silva Representacoes C. (RJ Interior)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('80671 - Guilherme Aleixo Neves de Oliveira - ME (Norte de Minas)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('80701 - AHSI Representacao Ltda - EPP (RJ Capital)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('80713 - Filgueiras Representacao Ltda - ME  (Zona da Mata)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('80729 - JCIC Novaes Representacoes Eireli - ME (RJ Capital)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('80734 - J P Silva Representacoes Eireli - ME (RJ Capital)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('80744 - Sartorato Representacoes Comerciais Ltda ME (SP Interior)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('80753 - Luiz Guilherme Gomes de Assis (Vale do Aço)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('80758 - R.F. de Lemos Representacao Comercial - ME (RJ Interior)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('80767 - Rodrigo Marcelo Biazotto - ME (SP Interior)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('80780 - F A de Oliveira Representacao Comercial - ME (BH)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('80786 - Rildo Martins Chicrala (CENTRO OESTE)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('80789 - Eduardo Carlos Ferreira  (Zona da Mata)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('80794 - Carlos Alberto de Souza Representacoes ME (SP Capital)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('80795 - Bruna Junqueira Goncalves - ME (Sul de Minas)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('80796 - Antonio Trajano da Silva Filho - ME (SP Capital)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('80799 - Wagner Vendramin - ME (SP Capital)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('80808 - AP Representações de Alimentos Ltda - ME (SP Capital)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('80814 - Aguinaldo Marreto (SP Capital)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('80817 - Maria Tereza Carvalho CPF- 819694656-20 - ME (BH)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('80820 - Marcelo Assis Silva da Conceicao Rep. Com. ME (BH)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('80828 - Gentil Souza Representacao Comercial - ME (SP Interior)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('80830 - Carlos Antonio Simoes (BH)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('80844 - Welton Chacara Soares - ME (Vale do Aço)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('80853 - R Nogueira Representacoes Ltda (SP Capital)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('80856 - J e R Representacoes Ltda ME (Sup. Gerência)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('80862 - Paulo Cezar Matos dos Santos - ME (Bahia)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('80871 - Humberto Leonardo Cabral Moura - ME (Goias)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('80875 - Debora Tais dos Santos Costa Ltda - ME (DF)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('80877 - Marcio Fabiano Oliveira 09913941601 - ME (Norte de Minas)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('80885 - Nascentes Correia Repres. Comerciais Ltda EPP (Vale do Aço)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('80891 - Ana Paula Lemes Adriano - ME (Sul de Minas)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('80907 - Costa e Assumpcao Representacao Ltda - ME (SP Capital)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('80908 - Pozzi de Miranda Representacao Eireli - ME (SP Capital)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('80911 - Celio e Cia Representacoes Ltda - ME (Triangulo Mineiro)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('80931 - William Miranda Ribeiro de Sa (RJ Interior)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('80943 - A J F Cruz Representacao Comercial - ME (RJ Capital)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('80945 - M A Representacao Comercial Ltda - Me (Alto Paranaiba)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('80948 - Wanderson dos Santos Eringe (RJ Interior)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('80950 - Walter Britto da Silva (RJ Capital)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('80952 - Cincerre Representacao Ltda ME (SP Interior)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('80957 - Alexsandro S de Almeida Representacoes - ME (Bahia)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('80959 - Carlos Daniel Coelho - ME  (Zona da Mata)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('80962 - E M Souza Junior LTDA - ME (Bahia)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('80963 - Douglas Lima Da Silva - ME (Bahia)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('80971 - Maantsil Representacao Comercial Ltda ME (SP Capital)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('80977 - R L Aparecido Granja (SP Capital)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('80981 - Luan Siqueira Santos - ME (Norte de Minas)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('80984 - M J R Guimaraes Representacao Comercial - ME (SP Capital)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('80987 - B da Cruz Neto Representacao Comercial - ME (RJ Interior)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('80989 - Milton Cunha Representacoes e Locacoes Ltda ME (Alto P.)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('80994 - Absolut Representacoes Ltda - ME (Goias)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('810006 - Lucas Luiz Representacoes Ltda Me (SP Capital)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('810011 - Maris Bastos Representacoes Ltda Me (BH)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('810017 - Elton S Da Silva - Me  (Bahia)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('810021 - AVF Representacoes Comerciais Ltda (RJ Capital)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('810026 - Andre L V Guimaraes Me (Bahia)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('810027 - S A Souza Representações Comerciais Ltda (Bahia)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('810050 - DS Representações Ltda (CENTRO OESTE)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('810056 - M Z Reis Representacoes Ltda Me (SP Capital)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('810067 - R&A Resende Representacoes Ltda ME (Triangulo Mineiro)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('810069 - Minas Uai Representacoes Ltda Me (BH)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('810070 - Sergio Luis Nunes - ME (Alto Paranaiba)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('810075 - Talita Ferreira Costa - ME  (Zona da Mata)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('810078 - Amador Jose de Queiroz Neto ME (Triangulo Mineiro)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('810081 - RSR Representações Ltda-ME (Bahia)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('810089 - Suelen de Menezes Pinto Magalhaes (RJ Interior)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('810091 - Tiago Diniz Consult E Rep Ltda (Bahia)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('810098 - L Ferreira dos Santos Sena Ltda (Bahia)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('810101 - Meire Monteiro Representacoes Ltda (Triangulo Mineiro)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('810102 - MM Representacoes Sacramento Ltda (Triangulo Mineiro)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('810103 - Nascentes Cunha Representacoes Ltda (Triangulo Mineiro)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('810105 - Ativa Representacoes de Alimentos Ltda (Bahia)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('810106 - WGS Representacoes Ltda (Triangulo Mineiro)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('810118 - CN Representações Ltda (DF)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('810120 - Santos e Silva Representações Ltda (Norte de Minas)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('810124 - Gilmar Alves dos Santos (Norte de Minas)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('810125 - Karollynne Rodrigues Silva') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('810127 - Roma Representação Ltda (Goias)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('810128 - Planeta Representação Ltda (Goias)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('810129 - WS C Representações e Comercio Ltda (Norte de Minas)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('810130 - Alex Almeida Duarte Representação (Bahia)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('810131 - Abul Representações Ltda (Goias)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('810147 - Gama Rio Representações Comerciais Ltda (RJ Capital)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('810149 - KB Representações Ltda (Goias)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('810150 - M A Borges (Triangulo Mineiro)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('810157 - André Luis Monferrari (RJ Interior)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('810161 - Jose Francisco de Favari Ltda (SP Interior)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('810164 - I C Guerra Alves & Cia Ltda (Bahia)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('810167 - SL Empreendimentos e Representações Ltda (BH)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('810170 - Moraes & Cristal Representações S/C Ltda (SP Interior)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('810178 - Castro Silva Representação Comercial Ltda (Alto Paranaiba)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('80934 - Cabidele Star Representacoes Ltda EPP (Espirito Santo)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('810189 - Reboucas Filho Representação Comercial Ltda (Bahia)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('810208 - Matheus Pereira Santos Representações LTDA (Norte de Minas)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('810209 - Fábio Luís Hipólito Vianna (SP Interior)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('810211 - CMC Representações (Sul de Minas)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('810215 - Jeane Carla de Oliveira Marcos  (Zona da Mata)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('810216 - Manhaes Representações LTDA (Norte de Minas)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('810217 - Isaías de Oliveira Júnior Representações (Vale do Aço)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('810222 - Jose Carlos Ferreira Nunes (Vale do Aço)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('810229 - V.D.S. Garcia LTDA (DF)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('810230 - FHA Representações  (Zona da Mata)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('810239 - Emanuel Soares dos Santos Avila (Espirito Santo)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('810247 - Asevedo Representações LTDA (Goiás)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('810250 - J Kid Representações (DF)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('810252 - Thulio Henrique Representação LTDA (DF)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('810254 - SGD2 Representações Comerciais LTDA (Goiás)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('810257 - Fernando Augusto de Lima (Vale do Aço)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('810261 - Jose Raimundo Guedes da Mota (Norte de Minas)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('810270 - Pires & Representacao LTDA (Goias)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('810288 - Elshaday Representações Comerciais LTDA (DF)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('810289 - Ima Representações LTDA (Bahia)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('810295 - Anjolera Representações Ltda (Centro Oeste)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('810297 - Sérgio Teixeira da Rocha (RJ Capital)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('810309 - RGI Representações LTDA (Goiás)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('80722 - NG Representacoes Ltda (Norte de Minas)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('810313 - Gustavo Arantes Lage (Sul de Minas)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('810314 - Cristiano Paiva Representações Ltda (Norte de Minas)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('810318 - Kleber Moraes Cavalcanti (Norte de Minas)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('810308 - Maria Aparecida dos Santos Nogueira Representação (BH)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('810296 - LC Braga Representações LTDA (Zona da Mata)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('80738 - Buona Vita Representacoes de Alimentos Ltda ME (SP Int)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('810322 - Fortes Representações Comercial Ltda (Espírito Santo)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('810325 - Venturatto Representações e Logística Ltda (Bahia)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('810328 - E. Veronese ME (São Paulo)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('810333 - I. A. do Carmo (Bahia)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('810334 - A&L Representações Ltda (Bahia)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('80603 - Robson Mendes Alexandre - Me (São Paulo)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('80719 - Cas Representante (Bahia)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('810342 - C.S.S Comercio e Representação Ltda (Bahia)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('80733 - CMCN Representacoes e Servicos Ltda - ME (Bahia)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('810348 - José Luiz Fernandes Filho - ME (DF)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('810263 - CB Negócios & Representações LTDA (DF)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('810350 - Aidar e Filhos Serviços de Rep Ltda (Triangulo Mineiro)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('810354 - J V S Fenix Consultoria e Rep Ltda (SP)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('810353 - Edvan dos Santos Correia (Bahia)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('80342 - Siempre Tecnologia e Representacoes Ltda (Triangulo Mineiro)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('810359 - Vander Alves Moreira (DF)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('810361 - C Alberto da Silva Representação Comercial (RJ Capital)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('810362 - Mayke Aguiar Fernandes') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('810364 - José Max Carvalho Naves (Rj Interior)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('810367 - M A Rosa Rep Comerciais e Comercio Ltda (RJ Interior)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('810368 - PC Representações Comerciais Ltda (Belo Horizonte)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('80685 - Adriano Leonardo dos Reis (Sul de Minas)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('810370 - Murilo Firmino Ribeiro Nogueira (Sul de Minas)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('80619 - Jcs Representacao Comercial Ltda ME (Goias)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('810372 - Euler Romualdo da Costa dos Santos Representações (BH)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('810033 - WA Guimarães Representante Comercial (Sul de Minas)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('810378 - CJR Representacoes Comerciais (BA)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('810379 - Janir Gomes de Oliveira 60546581668 (Zona da Mata)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('810181 - P. A. B. Representações Ltda (Espirito Santo)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('810384 - Z.M. Representações LTDA (RJ Capital)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('810386 -  LED Representacao Comercial e Eventos Esportivos Ltda (DF)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('810387 - Leandro Fernandes de Souza - (Norte de Minas)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('810389 - Barão Comercio e Representações - (Sul de Minas)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('810390 - Magno Alves Souza (Espirito Santo)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('810392 - NMT Silva Comercio e Representações (SP Capital)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('80599 - Santunes Representacoes - Eireli (SP)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('810204 - BMGG Representações Comerciais LTDA ME (RJ Capital)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('810395 - D''Beiços Representações (Vale do Aço)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('810396 - Lima Representação (Bahia)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('810398 - Thomag Representações Comerciais (PA)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('810399 - C M Borba Representações (SP Capital)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('810400 - FA Ribeiro Neto Representações (Espirito Santo)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('810401 - A DE B M da Costa Águia Representações  (Espirito Santo)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('810402 - Edirlei Juliano de Souza (Sul de Minas)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('810176 - Fernando Francisco da Silva Representações (Sul de Minas)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('810407 - Pablo Cazzola LTDA (SP Capital)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('810408 - Representação e Serviços Caetano (Goias)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('80124 - Leiz da Silva Figueiredo') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('810336 - Alves & Santana Rep Comerciais de Frios Ltda (Bahia)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('810413 - Wander De Araujo Santos (Vale do Aço)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('80712 - Jalem Jose Santos Magalhaes  (Zona da Mata)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('810415 - E.M Casteluber Representações (Espirito Santo)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('810391 - ACR Representações (Espirito Santo)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('810409 - Viviane R. Dias Campos Representações (BH)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('810410 - VLCB Representações (BH)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('810412 - Lucas Santos Moreira (Vale do Aço)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('810420 - Rodrigo Dourado Machado (Goias)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('810417 - Wedja da Silva S Costa (Bahia)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('810416 - Mac Jet Drones LTDA (RJ interior)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('810418 - Santiago & Bernardi Representações LTDA ( SP Interior)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('810423 - Wa Guimaraes Representacao Comercial LTDA (Sul de Minas)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('810424 - Hib Itaborai Representacoes Comercias LTDA (RJ Interior)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('810431 - Thierry Neves Batista (Bahia)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('810429 - Naidson Francis Melo (BH)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('810430 - Luciene Maria dos Santos (BH)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('80391 - Leila Viviane da Silva') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('810427 - Jose Flavio de Carvalho Junior (Sul de Minas)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('810428 - Douglas da Silva Oliveira (Zona da Mata)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('810426 - Juliana Azevedo Lopes (BH)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('810432 - Elisete RC Santos Representações (BH)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('810433 - GP Mais Comercio e Representação (Sp Capital)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('810434 - Nexus Representações LTDA (CENTRO OESTE)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('810435 - Paloma Stefani Batista Ferreira (Vale do Aço)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('810437 - Jm Representacoes (Goias)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('810422 - E Motta Representacoes LTDA (Sul de Minas)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('810450 - Vidal Servicos e Representacoes Comerciais LTDA (Rj Capital)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('810440 - WJS Representações LTDA (Goiás)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('810447 - J.A Ribeiro Representações (Goias)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('810448 - Wellington Silva Lopes (Goias)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('810441 - Herbert Diego Novais Ribeiro LTDA (Bahia)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('810449 - M & Morais Representacoes LTDA (Triangulo Mineiro)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('810439 - Melo Comércio e Representações LTDA (CENTRO OESTE)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('810445 - Jean P S Fernandes Representante (Vale do Aço)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('810446 - Polo Representações Comerciais (RJ Interior)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('810438 - Luiz Bertolini Netto Representações LTDA (SP Interior)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('810442 - J Bacani Representações (SP Interior)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('810443 - VCR Representações Comerciais (SP Interior)') ON CONFLICT DO NOTHING;
INSERT INTO dim_representantes (nome) VALUES ('810444 - Thiago Alexandro Cunha (SP Interior)') ON CONFLICT DO NOTHING;
