-- =====================================================================
-- 033 — O TEMPLATE DA SEMANA, DAS PLANILHAS PARA O PAINEL (24/08/2026)
-- ---------------------------------------------------------------------
-- Fonte: as cinco planilhas "Programação de Carregamento" de 17 a
-- 21/08/2026 — segunda a sexta, o processo real de hoje.
--
-- DECISÃO: os códigos são os que JÁ EXISTIAM no painel. A coluna "Rota"
-- da planilha é PRAÇA + TRANSPORTADORA ("Rio de Janeiro - Ômega X"); o
-- cadastro do painel é a PRAÇA ("517 Rio de Janeiro (Varejo)"). Foi o
-- nome da transportadora que, numa primeira leitura, me fez enxergar 50
-- rotas novas onde existiam ~25 praças já cadastradas.
--
-- O NOME ORIGINAL DA PLANILHA VAI EM `observacoes`, linha por linha.
-- Sem isso, mapear "Brasília - Pantanal" e "Brasília - Versatto" para o
-- mesmo 519 apagaria a transportadora — que é justamente o que a
-- Logística usa para reconhecer a carga. O código organiza; o nome
-- preserva.
--
-- ROTAS SEM PRAÇA CORRESPONDENTE ficaram DE FORA e estão listadas no fim
-- deste arquivo. Inventar código para elas seria pior que deixá-las
-- visíveis: são cinco linhas que a Logística cadastra na tela nova em
-- dois minutos, sabendo o que está fazendo.
--
-- O MODELO É PONTO DE PARTIDA. Sai de uma semana. A tela "Rotas por dia
-- da semana" edita; mudança vale para as próximas semanas.
--
-- ON CONFLICT DO NOTHING: rodar de novo não duplica, e o que a Logística
-- ajustar pela tela sobrevive a uma reaplicação.
-- =====================================================================


-- segunda — 13 cargas
INSERT INTO programacao_modelo (dia_semana, rota_codigo, ordem, tipo_operacao, qtd_entregas, paletizada, observacoes, criado_por) SELECT 1,'517',0,'CROSS-DOCKING',87,'Sim','Rio de Janeiro - Ômega X','planilha 17-21/08' WHERE EXISTS (SELECT 1 FROM dim_rotas WHERE codigo = '517') ON CONFLICT (dia_semana, rota_codigo, ordem) DO NOTHING;
INSERT INTO programacao_modelo (dia_semana, rota_codigo, ordem, tipo_operacao, qtd_entregas, paletizada, observacoes, criado_por) SELECT 1,'517',1,'CROSS-DOCKING',63,'Sim','Rio de Janeiro - Ômega X','planilha 17-21/08' WHERE EXISTS (SELECT 1 FROM dim_rotas WHERE codigo = '517') ON CONFLICT (dia_semana, rota_codigo, ordem) DO NOTHING;
INSERT INTO programacao_modelo (dia_semana, rota_codigo, ordem, tipo_operacao, qtd_entregas, paletizada, observacoes, criado_por) SELECT 1,'500',0,'',49,'Não','Patos de Minas','planilha 17-21/08' WHERE EXISTS (SELECT 1 FROM dim_rotas WHERE codigo = '500') ON CONFLICT (dia_semana, rota_codigo, ordem) DO NOTHING;
INSERT INTO programacao_modelo (dia_semana, rota_codigo, ordem, tipo_operacao, qtd_entregas, paletizada, observacoes, criado_por) SELECT 1,'500',1,'',31,'Não','Patos de Minas','planilha 17-21/08' WHERE EXISTS (SELECT 1 FROM dim_rotas WHERE codigo = '500') ON CONFLICT (dia_semana, rota_codigo, ordem) DO NOTHING;
INSERT INTO programacao_modelo (dia_semana, rota_codigo, ordem, tipo_operacao, qtd_entregas, paletizada, observacoes, criado_por) SELECT 1,'501',0,'',35,'Não','São Gotardo','planilha 17-21/08' WHERE EXISTS (SELECT 1 FROM dim_rotas WHERE codigo = '501') ON CONFLICT (dia_semana, rota_codigo, ordem) DO NOTHING;
INSERT INTO programacao_modelo (dia_semana, rota_codigo, ordem, tipo_operacao, qtd_entregas, paletizada, observacoes, criado_por) SELECT 1,'501',1,'',50,'Não','São Gotardo','planilha 17-21/08' WHERE EXISTS (SELECT 1 FROM dim_rotas WHERE codigo = '501') ON CONFLICT (dia_semana, rota_codigo, ordem) DO NOTHING;
INSERT INTO programacao_modelo (dia_semana, rota_codigo, ordem, tipo_operacao, qtd_entregas, paletizada, observacoes, criado_por) SELECT 1,'505',0,'CROSS-DOCKING',133,'Sim','Triângulo Mineiro - Total Service','planilha 17-21/08' WHERE EXISTS (SELECT 1 FROM dim_rotas WHERE codigo = '505') ON CONFLICT (dia_semana, rota_codigo, ordem) DO NOTHING;
INSERT INTO programacao_modelo (dia_semana, rota_codigo, ordem, tipo_operacao, qtd_entregas, paletizada, observacoes, criado_por) SELECT 1,'521',0,'CROSS-DOCKING',59,'Sim','Ribeirão Preto - Cargo Frio','planilha 17-21/08' WHERE EXISTS (SELECT 1 FROM dim_rotas WHERE codigo = '521') ON CONFLICT (dia_semana, rota_codigo, ordem) DO NOTHING;
INSERT INTO programacao_modelo (dia_semana, rota_codigo, ordem, tipo_operacao, qtd_entregas, paletizada, observacoes, criado_por) SELECT 1,'538',0,'CROSS-DOCKING',18,'Sim','Marília - Cargo Frio','planilha 17-21/08' WHERE EXISTS (SELECT 1 FROM dim_rotas WHERE codigo = '538') ON CONFLICT (dia_semana, rota_codigo, ordem) DO NOTHING;
INSERT INTO programacao_modelo (dia_semana, rota_codigo, ordem, tipo_operacao, qtd_entregas, paletizada, observacoes, criado_por) SELECT 1,'510',0,'CROSS-DOCKING',62,'Sim','Belo Horizonte - RP Express','planilha 17-21/08' WHERE EXISTS (SELECT 1 FROM dim_rotas WHERE codigo = '510') ON CONFLICT (dia_semana, rota_codigo, ordem) DO NOTHING;
INSERT INTO programacao_modelo (dia_semana, rota_codigo, ordem, tipo_operacao, qtd_entregas, paletizada, observacoes, criado_por) SELECT 1,'519',0,'CROSS-DOCKING',10,'Sim','Brasília - Pantanal','planilha 17-21/08' WHERE EXISTS (SELECT 1 FROM dim_rotas WHERE codigo = '519') ON CONFLICT (dia_semana, rota_codigo, ordem) DO NOTHING;
INSERT INTO programacao_modelo (dia_semana, rota_codigo, ordem, tipo_operacao, qtd_entregas, paletizada, observacoes, criado_por) SELECT 1,'519',1,'CROSS-DOCKING',55,'Sim','Brasília - Versatto','planilha 17-21/08' WHERE EXISTS (SELECT 1 FROM dim_rotas WHERE codigo = '519') ON CONFLICT (dia_semana, rota_codigo, ordem) DO NOTHING;
INSERT INTO programacao_modelo (dia_semana, rota_codigo, ordem, tipo_operacao, qtd_entregas, paletizada, observacoes, criado_por) SELECT 1,'525',0,'CROSS-DOCKING',76,'Sim','Bahia Capital-Log Master','planilha 17-21/08' WHERE EXISTS (SELECT 1 FROM dim_rotas WHERE codigo = '525') ON CONFLICT (dia_semana, rota_codigo, ordem) DO NOTHING;

-- terça — 26 cargas
INSERT INTO programacao_modelo (dia_semana, rota_codigo, ordem, tipo_operacao, qtd_entregas, paletizada, observacoes, criado_por) SELECT 2,'517',0,'',1,'Sim','Floresta - RJ','planilha 17-21/08' WHERE EXISTS (SELECT 1 FROM dim_rotas WHERE codigo = '517') ON CONFLICT (dia_semana, rota_codigo, ordem) DO NOTHING;
INSERT INTO programacao_modelo (dia_semana, rota_codigo, ordem, tipo_operacao, qtd_entregas, paletizada, observacoes, criado_por) SELECT 2,'517',1,'',1,'Sim','Adonai - RJ','planilha 17-21/08' WHERE EXISTS (SELECT 1 FROM dim_rotas WHERE codigo = '517') ON CONFLICT (dia_semana, rota_codigo, ordem) DO NOTHING;
INSERT INTO programacao_modelo (dia_semana, rota_codigo, ordem, tipo_operacao, qtd_entregas, paletizada, observacoes, criado_por) SELECT 2,'509',0,'CROSS-DOCKING',218,'Sim','6 Rotas-Centro Oeste','planilha 17-21/08' WHERE EXISTS (SELECT 1 FROM dim_rotas WHERE codigo = '509') ON CONFLICT (dia_semana, rota_codigo, ordem) DO NOTHING;
INSERT INTO programacao_modelo (dia_semana, rota_codigo, ordem, tipo_operacao, qtd_entregas, paletizada, observacoes, criado_por) SELECT 2,'509',1,'',1,'Sim','Adição - Divinopolis','planilha 17-21/08' WHERE EXISTS (SELECT 1 FROM dim_rotas WHERE codigo = '509') ON CONFLICT (dia_semana, rota_codigo, ordem) DO NOTHING;
INSERT INTO programacao_modelo (dia_semana, rota_codigo, ordem, tipo_operacao, qtd_entregas, paletizada, observacoes, criado_por) SELECT 2,'500',0,'',28,'Não','Patos de Minas','planilha 17-21/08' WHERE EXISTS (SELECT 1 FROM dim_rotas WHERE codigo = '500') ON CONFLICT (dia_semana, rota_codigo, ordem) DO NOTHING;
INSERT INTO programacao_modelo (dia_semana, rota_codigo, ordem, tipo_operacao, qtd_entregas, paletizada, observacoes, criado_por) SELECT 2,'500',1,'',38,'Não','Patos de Minas','planilha 17-21/08' WHERE EXISTS (SELECT 1 FROM dim_rotas WHERE codigo = '500') ON CONFLICT (dia_semana, rota_codigo, ordem) DO NOTHING;
INSERT INTO programacao_modelo (dia_semana, rota_codigo, ordem, tipo_operacao, qtd_entregas, paletizada, observacoes, criado_por) SELECT 2,'516',0,'CROSS-DOCKING',188,'Sim','Montes Claros - Mult Service','planilha 17-21/08' WHERE EXISTS (SELECT 1 FROM dim_rotas WHERE codigo = '516') ON CONFLICT (dia_semana, rota_codigo, ordem) DO NOTHING;
INSERT INTO programacao_modelo (dia_semana, rota_codigo, ordem, tipo_operacao, qtd_entregas, paletizada, observacoes, criado_por) SELECT 2,'516',1,'CROSS-DOCKING',148,'Sim','Montes Claros - Mult Service','planilha 17-21/08' WHERE EXISTS (SELECT 1 FROM dim_rotas WHERE codigo = '516') ON CONFLICT (dia_semana, rota_codigo, ordem) DO NOTHING;
INSERT INTO programacao_modelo (dia_semana, rota_codigo, ordem, tipo_operacao, qtd_entregas, paletizada, observacoes, criado_por) SELECT 2,'522',0,'CROSS-DOCKING',181,'Sim','SP Capital - SPM Log','planilha 17-21/08' WHERE EXISTS (SELECT 1 FROM dim_rotas WHERE codigo = '522') ON CONFLICT (dia_semana, rota_codigo, ordem) DO NOTHING;
INSERT INTO programacao_modelo (dia_semana, rota_codigo, ordem, tipo_operacao, qtd_entregas, paletizada, observacoes, criado_por) SELECT 2,'536',0,'CROSS-DOCKING',65,'Sim','Goiás - AG Sesttine','planilha 17-21/08' WHERE EXISTS (SELECT 1 FROM dim_rotas WHERE codigo = '536') ON CONFLICT (dia_semana, rota_codigo, ordem) DO NOTHING;
INSERT INTO programacao_modelo (dia_semana, rota_codigo, ordem, tipo_operacao, qtd_entregas, paletizada, observacoes, criado_por) SELECT 2,'505',0,'CROSS-DOCKING',158,'Sim','Triângulo Mineiro - Total Service','planilha 17-21/08' WHERE EXISTS (SELECT 1 FROM dim_rotas WHERE codigo = '505') ON CONFLICT (dia_semana, rota_codigo, ordem) DO NOTHING;
INSERT INTO programacao_modelo (dia_semana, rota_codigo, ordem, tipo_operacao, qtd_entregas, paletizada, observacoes, criado_por) SELECT 2,'512',0,'CROSS-DOCKING',110,'Sim','Varginha - Brasfrios','planilha 17-21/08' WHERE EXISTS (SELECT 1 FROM dim_rotas WHERE codigo = '512') ON CONFLICT (dia_semana, rota_codigo, ordem) DO NOTHING;
INSERT INTO programacao_modelo (dia_semana, rota_codigo, ordem, tipo_operacao, qtd_entregas, paletizada, observacoes, criado_por) SELECT 2,'513',0,'CROSS-DOCKING',127,'Sim','Passos - Maxfrios','planilha 17-21/08' WHERE EXISTS (SELECT 1 FROM dim_rotas WHERE codigo = '513') ON CONFLICT (dia_semana, rota_codigo, ordem) DO NOTHING;
INSERT INTO programacao_modelo (dia_semana, rota_codigo, ordem, tipo_operacao, qtd_entregas, paletizada, observacoes, criado_por) SELECT 2,'517',2,'CROSS-DOCKING',118,'Sim','Rio de Janeiro - Ômega X','planilha 17-21/08' WHERE EXISTS (SELECT 1 FROM dim_rotas WHERE codigo = '517') ON CONFLICT (dia_semana, rota_codigo, ordem) DO NOTHING;
INSERT INTO programacao_modelo (dia_semana, rota_codigo, ordem, tipo_operacao, qtd_entregas, paletizada, observacoes, criado_por) SELECT 2,'518',0,'CROSS-DOCKING',53,'Sim','Assai - Kanejo - RJ','planilha 17-21/08' WHERE EXISTS (SELECT 1 FROM dim_rotas WHERE codigo = '518') ON CONFLICT (dia_semana, rota_codigo, ordem) DO NOTHING;
INSERT INTO programacao_modelo (dia_semana, rota_codigo, ordem, tipo_operacao, qtd_entregas, paletizada, observacoes, criado_por) SELECT 2,'504',0,'',26,'Não','Arinos / Buritis','planilha 17-21/08' WHERE EXISTS (SELECT 1 FROM dim_rotas WHERE codigo = '504') ON CONFLICT (dia_semana, rota_codigo, ordem) DO NOTHING;
INSERT INTO programacao_modelo (dia_semana, rota_codigo, ordem, tipo_operacao, qtd_entregas, paletizada, observacoes, criado_por) SELECT 2,'504',1,'',23,'Não','Riachinho','planilha 17-21/08' WHERE EXISTS (SELECT 1 FROM dim_rotas WHERE codigo = '504') ON CONFLICT (dia_semana, rota_codigo, ordem) DO NOTHING;
INSERT INTO programacao_modelo (dia_semana, rota_codigo, ordem, tipo_operacao, qtd_entregas, paletizada, observacoes, criado_por) SELECT 2,'504',2,'',42,'Não','João Pinheiro','planilha 17-21/08' WHERE EXISTS (SELECT 1 FROM dim_rotas WHERE codigo = '504') ON CONFLICT (dia_semana, rota_codigo, ordem) DO NOTHING;
INSERT INTO programacao_modelo (dia_semana, rota_codigo, ordem, tipo_operacao, qtd_entregas, paletizada, observacoes, criado_por) SELECT 2,'504',3,'',6,'Não','João Pinheiro 1','planilha 17-21/08' WHERE EXISTS (SELECT 1 FROM dim_rotas WHERE codigo = '504') ON CONFLICT (dia_semana, rota_codigo, ordem) DO NOTHING;
INSERT INTO programacao_modelo (dia_semana, rota_codigo, ordem, tipo_operacao, qtd_entregas, paletizada, observacoes, criado_por) SELECT 2,'504',4,'',46,'Não','Paracatu','planilha 17-21/08' WHERE EXISTS (SELECT 1 FROM dim_rotas WHERE codigo = '504') ON CONFLICT (dia_semana, rota_codigo, ordem) DO NOTHING;
INSERT INTO programacao_modelo (dia_semana, rota_codigo, ordem, tipo_operacao, qtd_entregas, paletizada, observacoes, criado_por) SELECT 2,'504',5,'',40,'Sim','Unaí','planilha 17-21/08' WHERE EXISTS (SELECT 1 FROM dim_rotas WHERE codigo = '504') ON CONFLICT (dia_semana, rota_codigo, ordem) DO NOTHING;
INSERT INTO programacao_modelo (dia_semana, rota_codigo, ordem, tipo_operacao, qtd_entregas, paletizada, observacoes, criado_por) SELECT 2,'502',0,'',42,'Não','Araxá','planilha 17-21/08' WHERE EXISTS (SELECT 1 FROM dim_rotas WHERE codigo = '502') ON CONFLICT (dia_semana, rota_codigo, ordem) DO NOTHING;
INSERT INTO programacao_modelo (dia_semana, rota_codigo, ordem, tipo_operacao, qtd_entregas, paletizada, observacoes, criado_por) SELECT 2,'502',1,'',41,'Não','Araxá 2','planilha 17-21/08' WHERE EXISTS (SELECT 1 FROM dim_rotas WHERE codigo = '502') ON CONFLICT (dia_semana, rota_codigo, ordem) DO NOTHING;
INSERT INTO programacao_modelo (dia_semana, rota_codigo, ordem, tipo_operacao, qtd_entregas, paletizada, observacoes, criado_por) SELECT 2,'502',2,'',10,'Não','Araxá 3','planilha 17-21/08' WHERE EXISTS (SELECT 1 FROM dim_rotas WHERE codigo = '502') ON CONFLICT (dia_semana, rota_codigo, ordem) DO NOTHING;
INSERT INTO programacao_modelo (dia_semana, rota_codigo, ordem, tipo_operacao, qtd_entregas, paletizada, observacoes, criado_por) SELECT 2,'503',0,'',57,'Não','Patrocínio','planilha 17-21/08' WHERE EXISTS (SELECT 1 FROM dim_rotas WHERE codigo = '503') ON CONFLICT (dia_semana, rota_codigo, ordem) DO NOTHING;
INSERT INTO programacao_modelo (dia_semana, rota_codigo, ordem, tipo_operacao, qtd_entregas, paletizada, observacoes, criado_por) SELECT 2,'503',1,'',41,'Não','Coromandel','planilha 17-21/08' WHERE EXISTS (SELECT 1 FROM dim_rotas WHERE codigo = '503') ON CONFLICT (dia_semana, rota_codigo, ordem) DO NOTHING;

-- quarta — 11 cargas
INSERT INTO programacao_modelo (dia_semana, rota_codigo, ordem, tipo_operacao, qtd_entregas, paletizada, observacoes, criado_por) SELECT 3,'509',0,'',NULL,'Não','Centro Oeste','planilha 17-21/08' WHERE EXISTS (SELECT 1 FROM dim_rotas WHERE codigo = '509') ON CONFLICT (dia_semana, rota_codigo, ordem) DO NOTHING;
INSERT INTO programacao_modelo (dia_semana, rota_codigo, ordem, tipo_operacao, qtd_entregas, paletizada, observacoes, criado_por) SELECT 3,'505',0,'',NULL,'Não','Triângulo Mineiro - Total Service','planilha 17-21/08' WHERE EXISTS (SELECT 1 FROM dim_rotas WHERE codigo = '505') ON CONFLICT (dia_semana, rota_codigo, ordem) DO NOTHING;
INSERT INTO programacao_modelo (dia_semana, rota_codigo, ordem, tipo_operacao, qtd_entregas, paletizada, observacoes, criado_por) SELECT 3,'519',0,'',NULL,'Não','Brasília - Pantanal','planilha 17-21/08' WHERE EXISTS (SELECT 1 FROM dim_rotas WHERE codigo = '519') ON CONFLICT (dia_semana, rota_codigo, ordem) DO NOTHING;
INSERT INTO programacao_modelo (dia_semana, rota_codigo, ordem, tipo_operacao, qtd_entregas, paletizada, observacoes, criado_por) SELECT 3,'519',1,'',NULL,'Não','Brasília - Versatto','planilha 17-21/08' WHERE EXISTS (SELECT 1 FROM dim_rotas WHERE codigo = '519') ON CONFLICT (dia_semana, rota_codigo, ordem) DO NOTHING;
INSERT INTO programacao_modelo (dia_semana, rota_codigo, ordem, tipo_operacao, qtd_entregas, paletizada, observacoes, criado_por) SELECT 3,'500',0,'',NULL,'Não','Patos de Minas','planilha 17-21/08' WHERE EXISTS (SELECT 1 FROM dim_rotas WHERE codigo = '500') ON CONFLICT (dia_semana, rota_codigo, ordem) DO NOTHING;
INSERT INTO programacao_modelo (dia_semana, rota_codigo, ordem, tipo_operacao, qtd_entregas, paletizada, observacoes, criado_por) SELECT 3,'500',1,'',NULL,'Não','Patos de Minas','planilha 17-21/08' WHERE EXISTS (SELECT 1 FROM dim_rotas WHERE codigo = '500') ON CONFLICT (dia_semana, rota_codigo, ordem) DO NOTHING;
INSERT INTO programacao_modelo (dia_semana, rota_codigo, ordem, tipo_operacao, qtd_entregas, paletizada, observacoes, criado_por) SELECT 3,'501',0,'',NULL,'Não','São Gotardo','planilha 17-21/08' WHERE EXISTS (SELECT 1 FROM dim_rotas WHERE codigo = '501') ON CONFLICT (dia_semana, rota_codigo, ordem) DO NOTHING;
INSERT INTO programacao_modelo (dia_semana, rota_codigo, ordem, tipo_operacao, qtd_entregas, paletizada, observacoes, criado_por) SELECT 3,'501',1,'',NULL,'Não','São Gotardo','planilha 17-21/08' WHERE EXISTS (SELECT 1 FROM dim_rotas WHERE codigo = '501') ON CONFLICT (dia_semana, rota_codigo, ordem) DO NOTHING;
INSERT INTO programacao_modelo (dia_semana, rota_codigo, ordem, tipo_operacao, qtd_entregas, paletizada, observacoes, criado_por) SELECT 3,'510',0,'',NULL,'Não','Belo Horizonte - RP Express','planilha 17-21/08' WHERE EXISTS (SELECT 1 FROM dim_rotas WHERE codigo = '510') ON CONFLICT (dia_semana, rota_codigo, ordem) DO NOTHING;
INSERT INTO programacao_modelo (dia_semana, rota_codigo, ordem, tipo_operacao, qtd_entregas, paletizada, observacoes, criado_por) SELECT 3,'517',0,'',NULL,'Não','Rio de Janeiro - Ômega X','planilha 17-21/08' WHERE EXISTS (SELECT 1 FROM dim_rotas WHERE codigo = '517') ON CONFLICT (dia_semana, rota_codigo, ordem) DO NOTHING;
INSERT INTO programacao_modelo (dia_semana, rota_codigo, ordem, tipo_operacao, qtd_entregas, paletizada, observacoes, criado_por) SELECT 3,'517',1,'',NULL,'Não','Rio de Janeiro - Ômega X','planilha 17-21/08' WHERE EXISTS (SELECT 1 FROM dim_rotas WHERE codigo = '517') ON CONFLICT (dia_semana, rota_codigo, ordem) DO NOTHING;

-- quinta — 12 cargas
INSERT INTO programacao_modelo (dia_semana, rota_codigo, ordem, tipo_operacao, qtd_entregas, paletizada, observacoes, criado_por) SELECT 4,'510',0,'',NULL,'Não','Belo Horinzonte- RP Express','planilha 17-21/08' WHERE EXISTS (SELECT 1 FROM dim_rotas WHERE codigo = '510') ON CONFLICT (dia_semana, rota_codigo, ordem) DO NOTHING;
INSERT INTO programacao_modelo (dia_semana, rota_codigo, ordem, tipo_operacao, qtd_entregas, paletizada, observacoes, criado_por) SELECT 4,'012',0,'',NULL,'Não','Force Meat - RJ','planilha 17-21/08' WHERE EXISTS (SELECT 1 FROM dim_rotas WHERE codigo = '012') ON CONFLICT (dia_semana, rota_codigo, ordem) DO NOTHING;
INSERT INTO programacao_modelo (dia_semana, rota_codigo, ordem, tipo_operacao, qtd_entregas, paletizada, observacoes, criado_por) SELECT 4,'500',0,'',NULL,'Não','Patos de Minas','planilha 17-21/08' WHERE EXISTS (SELECT 1 FROM dim_rotas WHERE codigo = '500') ON CONFLICT (dia_semana, rota_codigo, ordem) DO NOTHING;
INSERT INTO programacao_modelo (dia_semana, rota_codigo, ordem, tipo_operacao, qtd_entregas, paletizada, observacoes, criado_por) SELECT 4,'500',1,'',NULL,'Não','Patos de Minas','planilha 17-21/08' WHERE EXISTS (SELECT 1 FROM dim_rotas WHERE codigo = '500') ON CONFLICT (dia_semana, rota_codigo, ordem) DO NOTHING;
INSERT INTO programacao_modelo (dia_semana, rota_codigo, ordem, tipo_operacao, qtd_entregas, paletizada, observacoes, criado_por) SELECT 4,'521',0,'',NULL,'Não','Ribeirão Preto - Cargo Frio','planilha 17-21/08' WHERE EXISTS (SELECT 1 FROM dim_rotas WHERE codigo = '521') ON CONFLICT (dia_semana, rota_codigo, ordem) DO NOTHING;
INSERT INTO programacao_modelo (dia_semana, rota_codigo, ordem, tipo_operacao, qtd_entregas, paletizada, observacoes, criado_por) SELECT 4,'538',0,'',NULL,'Não','Marília - Cargo Frio','planilha 17-21/08' WHERE EXISTS (SELECT 1 FROM dim_rotas WHERE codigo = '538') ON CONFLICT (dia_semana, rota_codigo, ordem) DO NOTHING;
INSERT INTO programacao_modelo (dia_semana, rota_codigo, ordem, tipo_operacao, qtd_entregas, paletizada, observacoes, criado_por) SELECT 4,'517',0,'',NULL,'Não','Rio de Janeiro - Ômega X','planilha 17-21/08' WHERE EXISTS (SELECT 1 FROM dim_rotas WHERE codigo = '517') ON CONFLICT (dia_semana, rota_codigo, ordem) DO NOTHING;
INSERT INTO programacao_modelo (dia_semana, rota_codigo, ordem, tipo_operacao, qtd_entregas, paletizada, observacoes, criado_por) SELECT 4,'517',1,'',NULL,'Não','Rio de Janeiro - Ômega X','planilha 17-21/08' WHERE EXISTS (SELECT 1 FROM dim_rotas WHERE codigo = '517') ON CONFLICT (dia_semana, rota_codigo, ordem) DO NOTHING;
INSERT INTO programacao_modelo (dia_semana, rota_codigo, ordem, tipo_operacao, qtd_entregas, paletizada, observacoes, criado_por) SELECT 4,'527',0,'',NULL,'Não','Nordeste 2','planilha 17-21/08' WHERE EXISTS (SELECT 1 FROM dim_rotas WHERE codigo = '527') ON CONFLICT (dia_semana, rota_codigo, ordem) DO NOTHING;
INSERT INTO programacao_modelo (dia_semana, rota_codigo, ordem, tipo_operacao, qtd_entregas, paletizada, observacoes, criado_por) SELECT 4,'532',0,'',NULL,'Não','Bahia Interior - TransVieira','planilha 17-21/08' WHERE EXISTS (SELECT 1 FROM dim_rotas WHERE codigo = '532') ON CONFLICT (dia_semana, rota_codigo, ordem) DO NOTHING;
INSERT INTO programacao_modelo (dia_semana, rota_codigo, ordem, tipo_operacao, qtd_entregas, paletizada, observacoes, criado_por) SELECT 4,'532',1,'',NULL,'Não','Bahia Interior - TransVieira','planilha 17-21/08' WHERE EXISTS (SELECT 1 FROM dim_rotas WHERE codigo = '532') ON CONFLICT (dia_semana, rota_codigo, ordem) DO NOTHING;
INSERT INTO programacao_modelo (dia_semana, rota_codigo, ordem, tipo_operacao, qtd_entregas, paletizada, observacoes, criado_por) SELECT 4,'527',1,'',NULL,'Não','Nordeste 1','planilha 17-21/08' WHERE EXISTS (SELECT 1 FROM dim_rotas WHERE codigo = '527') ON CONFLICT (dia_semana, rota_codigo, ordem) DO NOTHING;

-- sexta — 39 cargas
INSERT INTO programacao_modelo (dia_semana, rota_codigo, ordem, tipo_operacao, qtd_entregas, paletizada, observacoes, criado_por) SELECT 5,'517',0,'',2,'Sim','Floresta RJ','planilha 17-21/08' WHERE EXISTS (SELECT 1 FROM dim_rotas WHERE codigo = '517') ON CONFLICT (dia_semana, rota_codigo, ordem) DO NOTHING;
INSERT INTO programacao_modelo (dia_semana, rota_codigo, ordem, tipo_operacao, qtd_entregas, paletizada, observacoes, criado_por) SELECT 5,'518',0,'',1,'Sim','Guanabara - RJ','planilha 17-21/08' WHERE EXISTS (SELECT 1 FROM dim_rotas WHERE codigo = '518') ON CONFLICT (dia_semana, rota_codigo, ordem) DO NOTHING;
INSERT INTO programacao_modelo (dia_semana, rota_codigo, ordem, tipo_operacao, qtd_entregas, paletizada, observacoes, criado_por) SELECT 5,'518',1,'CROSS-DOCKING',78,'Sim','Assai - Kanejo RJ','planilha 17-21/08' WHERE EXISTS (SELECT 1 FROM dim_rotas WHERE codigo = '518') ON CONFLICT (dia_semana, rota_codigo, ordem) DO NOTHING;
INSERT INTO programacao_modelo (dia_semana, rota_codigo, ordem, tipo_operacao, qtd_entregas, paletizada, observacoes, criado_por) SELECT 5,'522',0,'',1,'Sim','GPA SP','planilha 17-21/08' WHERE EXISTS (SELECT 1 FROM dim_rotas WHERE codigo = '522') ON CONFLICT (dia_semana, rota_codigo, ordem) DO NOTHING;
INSERT INTO programacao_modelo (dia_semana, rota_codigo, ordem, tipo_operacao, qtd_entregas, paletizada, observacoes, criado_por) SELECT 5,'517',1,'CROSS-DOCKING',66,'Sim','Rio de Janeiro - Ômega X','planilha 17-21/08' WHERE EXISTS (SELECT 1 FROM dim_rotas WHERE codigo = '517') ON CONFLICT (dia_semana, rota_codigo, ordem) DO NOTHING;
INSERT INTO programacao_modelo (dia_semana, rota_codigo, ordem, tipo_operacao, qtd_entregas, paletizada, observacoes, criado_por) SELECT 5,'517',2,'CROSS-DOCKING',50,'Sim','Rio de Janeiro - Ômega X','planilha 17-21/08' WHERE EXISTS (SELECT 1 FROM dim_rotas WHERE codigo = '517') ON CONFLICT (dia_semana, rota_codigo, ordem) DO NOTHING;
INSERT INTO programacao_modelo (dia_semana, rota_codigo, ordem, tipo_operacao, qtd_entregas, paletizada, observacoes, criado_por) SELECT 5,'524',0,'CROSS-DOCKING',309,'Sim','Zona da Mata - BSF Logísitca','planilha 17-21/08' WHERE EXISTS (SELECT 1 FROM dim_rotas WHERE codigo = '524') ON CONFLICT (dia_semana, rota_codigo, ordem) DO NOTHING;
INSERT INTO programacao_modelo (dia_semana, rota_codigo, ordem, tipo_operacao, qtd_entregas, paletizada, observacoes, criado_por) SELECT 5,'524',1,'CROSS-DOCKING',102,'Sim','Zona da Mata - BSF Logísitca','planilha 17-21/08' WHERE EXISTS (SELECT 1 FROM dim_rotas WHERE codigo = '524') ON CONFLICT (dia_semana, rota_codigo, ordem) DO NOTHING;
INSERT INTO programacao_modelo (dia_semana, rota_codigo, ordem, tipo_operacao, qtd_entregas, paletizada, observacoes, criado_por) SELECT 5,'516',0,'CROSS-DOCKING',223,'Sim','Montes Claros - Total  Service','planilha 17-21/08' WHERE EXISTS (SELECT 1 FROM dim_rotas WHERE codigo = '516') ON CONFLICT (dia_semana, rota_codigo, ordem) DO NOTHING;
INSERT INTO programacao_modelo (dia_semana, rota_codigo, ordem, tipo_operacao, qtd_entregas, paletizada, observacoes, criado_por) SELECT 5,'516',1,'CROSS-DOCKING',229,'Sim','Montes Claros - Total  Service','planilha 17-21/08' WHERE EXISTS (SELECT 1 FROM dim_rotas WHERE codigo = '516') ON CONFLICT (dia_semana, rota_codigo, ordem) DO NOTHING;
INSERT INTO programacao_modelo (dia_semana, rota_codigo, ordem, tipo_operacao, qtd_entregas, paletizada, observacoes, criado_por) SELECT 5,'516',2,'CROSS-DOCKING',123,'Sim','Montes Claros - Total  Service','planilha 17-21/08' WHERE EXISTS (SELECT 1 FROM dim_rotas WHERE codigo = '516') ON CONFLICT (dia_semana, rota_codigo, ordem) DO NOTHING;
INSERT INTO programacao_modelo (dia_semana, rota_codigo, ordem, tipo_operacao, qtd_entregas, paletizada, observacoes, criado_por) SELECT 5,'516',3,'CROSS-DOCKING',95,'Sim','Montes Claros - Total  Service','planilha 17-21/08' WHERE EXISTS (SELECT 1 FROM dim_rotas WHERE codigo = '516') ON CONFLICT (dia_semana, rota_codigo, ordem) DO NOTHING;
INSERT INTO programacao_modelo (dia_semana, rota_codigo, ordem, tipo_operacao, qtd_entregas, paletizada, observacoes, criado_por) SELECT 5,'522',1,'CROSS-DOCKING',89,'Sim','Osasco - SPM Logística','planilha 17-21/08' WHERE EXISTS (SELECT 1 FROM dim_rotas WHERE codigo = '522') ON CONFLICT (dia_semana, rota_codigo, ordem) DO NOTHING;
INSERT INTO programacao_modelo (dia_semana, rota_codigo, ordem, tipo_operacao, qtd_entregas, paletizada, observacoes, criado_por) SELECT 5,'522',2,'CROSS-DOCKING',44,'Sim','Osasco - SPM Logística','planilha 17-21/08' WHERE EXISTS (SELECT 1 FROM dim_rotas WHERE codigo = '522') ON CONFLICT (dia_semana, rota_codigo, ordem) DO NOTHING;
INSERT INTO programacao_modelo (dia_semana, rota_codigo, ordem, tipo_operacao, qtd_entregas, paletizada, observacoes, criado_por) SELECT 5,'536',0,'CROSS-DOCKING',187,'Sim','Goias - AG Sestini','planilha 17-21/08' WHERE EXISTS (SELECT 1 FROM dim_rotas WHERE codigo = '536') ON CONFLICT (dia_semana, rota_codigo, ordem) DO NOTHING;
INSERT INTO programacao_modelo (dia_semana, rota_codigo, ordem, tipo_operacao, qtd_entregas, paletizada, observacoes, criado_por) SELECT 5,'536',1,'CROSS-DOCKING',39,'Sim','Goias - AG Sestini','planilha 17-21/08' WHERE EXISTS (SELECT 1 FROM dim_rotas WHERE codigo = '536') ON CONFLICT (dia_semana, rota_codigo, ordem) DO NOTHING;
INSERT INTO programacao_modelo (dia_semana, rota_codigo, ordem, tipo_operacao, qtd_entregas, paletizada, observacoes, criado_por) SELECT 5,'519',0,'CROSS-DOCKING',40,'Sim','Brasília - Versatto','planilha 17-21/08' WHERE EXISTS (SELECT 1 FROM dim_rotas WHERE codigo = '519') ON CONFLICT (dia_semana, rota_codigo, ordem) DO NOTHING;
INSERT INTO programacao_modelo (dia_semana, rota_codigo, ordem, tipo_operacao, qtd_entregas, paletizada, observacoes, criado_por) SELECT 5,'519',1,'CROSS-DOCKING',87,'Sim','Brasília - Versatto','planilha 17-21/08' WHERE EXISTS (SELECT 1 FROM dim_rotas WHERE codigo = '519') ON CONFLICT (dia_semana, rota_codigo, ordem) DO NOTHING;
INSERT INTO programacao_modelo (dia_semana, rota_codigo, ordem, tipo_operacao, qtd_entregas, paletizada, observacoes, criado_por) SELECT 5,'519',2,'CROSS-DOCKING',54,'Sim','Brasília - Pantanal','planilha 17-21/08' WHERE EXISTS (SELECT 1 FROM dim_rotas WHERE codigo = '519') ON CONFLICT (dia_semana, rota_codigo, ordem) DO NOTHING;
INSERT INTO programacao_modelo (dia_semana, rota_codigo, ordem, tipo_operacao, qtd_entregas, paletizada, observacoes, criado_por) SELECT 5,'510',0,'CROSS-DOCKING',113,'Sim','Belo Horizonte - RP Express','planilha 17-21/08' WHERE EXISTS (SELECT 1 FROM dim_rotas WHERE codigo = '510') ON CONFLICT (dia_semana, rota_codigo, ordem) DO NOTHING;
INSERT INTO programacao_modelo (dia_semana, rota_codigo, ordem, tipo_operacao, qtd_entregas, paletizada, observacoes, criado_por) SELECT 5,'512',0,'CROSS-DOCKING',119,'Sim','Varginha - Brasfrios','planilha 17-21/08' WHERE EXISTS (SELECT 1 FROM dim_rotas WHERE codigo = '512') ON CONFLICT (dia_semana, rota_codigo, ordem) DO NOTHING;
INSERT INTO programacao_modelo (dia_semana, rota_codigo, ordem, tipo_operacao, qtd_entregas, paletizada, observacoes, criado_por) SELECT 5,'513',0,'CROSS-DOCKING',34,'Sim','Passos - Maxfrios','planilha 17-21/08' WHERE EXISTS (SELECT 1 FROM dim_rotas WHERE codigo = '513') ON CONFLICT (dia_semana, rota_codigo, ordem) DO NOTHING;
INSERT INTO programacao_modelo (dia_semana, rota_codigo, ordem, tipo_operacao, qtd_entregas, paletizada, observacoes, criado_por) SELECT 5,'513',1,'CROSS-DOCKING',85,'Sim','Passos - Maxfrios','planilha 17-21/08' WHERE EXISTS (SELECT 1 FROM dim_rotas WHERE codigo = '513') ON CONFLICT (dia_semana, rota_codigo, ordem) DO NOTHING;
INSERT INTO programacao_modelo (dia_semana, rota_codigo, ordem, tipo_operacao, qtd_entregas, paletizada, observacoes, criado_por) SELECT 5,'523',0,'CROSS-DOCKING',207,'Sim','Vale do Aço - SS Log','planilha 17-21/08' WHERE EXISTS (SELECT 1 FROM dim_rotas WHERE codigo = '523') ON CONFLICT (dia_semana, rota_codigo, ordem) DO NOTHING;
INSERT INTO programacao_modelo (dia_semana, rota_codigo, ordem, tipo_operacao, qtd_entregas, paletizada, observacoes, criado_por) SELECT 5,'523',1,'CROSS-DOCKING',76,'Sim','Vale do Aço - SS Log','planilha 17-21/08' WHERE EXISTS (SELECT 1 FROM dim_rotas WHERE codigo = '523') ON CONFLICT (dia_semana, rota_codigo, ordem) DO NOTHING;
INSERT INTO programacao_modelo (dia_semana, rota_codigo, ordem, tipo_operacao, qtd_entregas, paletizada, observacoes, criado_por) SELECT 5,'505',0,'CROSS-DOCKING',151,'Sim','Triângulo Mineiro - Total Service','planilha 17-21/08' WHERE EXISTS (SELECT 1 FROM dim_rotas WHERE codigo = '505') ON CONFLICT (dia_semana, rota_codigo, ordem) DO NOTHING;
INSERT INTO programacao_modelo (dia_semana, rota_codigo, ordem, tipo_operacao, qtd_entregas, paletizada, observacoes, criado_por) SELECT 5,'505',1,'CROSS-DOCKING',58,'Sim','Triângulo Mineiro - Total Service','planilha 17-21/08' WHERE EXISTS (SELECT 1 FROM dim_rotas WHERE codigo = '505') ON CONFLICT (dia_semana, rota_codigo, ordem) DO NOTHING;
INSERT INTO programacao_modelo (dia_semana, rota_codigo, ordem, tipo_operacao, qtd_entregas, paletizada, observacoes, criado_por) SELECT 5,'529',0,'CROSS-DOCKING',44,'Sim','Espirito Santo - BemFrios','planilha 17-21/08' WHERE EXISTS (SELECT 1 FROM dim_rotas WHERE codigo = '529') ON CONFLICT (dia_semana, rota_codigo, ordem) DO NOTHING;
INSERT INTO programacao_modelo (dia_semana, rota_codigo, ordem, tipo_operacao, qtd_entregas, paletizada, observacoes, criado_por) SELECT 5,'525',0,'CROSS-DOCKING',84,'Sim','Bahia Capital - LogMaster','planilha 17-21/08' WHERE EXISTS (SELECT 1 FROM dim_rotas WHERE codigo = '525') ON CONFLICT (dia_semana, rota_codigo, ordem) DO NOTHING;
INSERT INTO programacao_modelo (dia_semana, rota_codigo, ordem, tipo_operacao, qtd_entregas, paletizada, observacoes, criado_por) SELECT 5,'500',0,'',33,'Não','Patos de Minas','planilha 17-21/08' WHERE EXISTS (SELECT 1 FROM dim_rotas WHERE codigo = '500') ON CONFLICT (dia_semana, rota_codigo, ordem) DO NOTHING;
INSERT INTO programacao_modelo (dia_semana, rota_codigo, ordem, tipo_operacao, qtd_entregas, paletizada, observacoes, criado_por) SELECT 5,'504',0,'',21,'Não','Arinos / Buritis','planilha 17-21/08' WHERE EXISTS (SELECT 1 FROM dim_rotas WHERE codigo = '504') ON CONFLICT (dia_semana, rota_codigo, ordem) DO NOTHING;
INSERT INTO programacao_modelo (dia_semana, rota_codigo, ordem, tipo_operacao, qtd_entregas, paletizada, observacoes, criado_por) SELECT 5,'504',1,'',27,'Não','Riachinho','planilha 17-21/08' WHERE EXISTS (SELECT 1 FROM dim_rotas WHERE codigo = '504') ON CONFLICT (dia_semana, rota_codigo, ordem) DO NOTHING;
INSERT INTO programacao_modelo (dia_semana, rota_codigo, ordem, tipo_operacao, qtd_entregas, paletizada, observacoes, criado_por) SELECT 5,'504',2,'',39,'Não','João Pinheiro','planilha 17-21/08' WHERE EXISTS (SELECT 1 FROM dim_rotas WHERE codigo = '504') ON CONFLICT (dia_semana, rota_codigo, ordem) DO NOTHING;
INSERT INTO programacao_modelo (dia_semana, rota_codigo, ordem, tipo_operacao, qtd_entregas, paletizada, observacoes, criado_por) SELECT 5,'504',3,'',38,'Não','Paracatu','planilha 17-21/08' WHERE EXISTS (SELECT 1 FROM dim_rotas WHERE codigo = '504') ON CONFLICT (dia_semana, rota_codigo, ordem) DO NOTHING;
INSERT INTO programacao_modelo (dia_semana, rota_codigo, ordem, tipo_operacao, qtd_entregas, paletizada, observacoes, criado_por) SELECT 5,'504',4,'',18,'Não','Unaí','planilha 17-21/08' WHERE EXISTS (SELECT 1 FROM dim_rotas WHERE codigo = '504') ON CONFLICT (dia_semana, rota_codigo, ordem) DO NOTHING;
INSERT INTO programacao_modelo (dia_semana, rota_codigo, ordem, tipo_operacao, qtd_entregas, paletizada, observacoes, criado_por) SELECT 5,'504',5,'',18,'Não','Unaí 2','planilha 17-21/08' WHERE EXISTS (SELECT 1 FROM dim_rotas WHERE codigo = '504') ON CONFLICT (dia_semana, rota_codigo, ordem) DO NOTHING;
INSERT INTO programacao_modelo (dia_semana, rota_codigo, ordem, tipo_operacao, qtd_entregas, paletizada, observacoes, criado_por) SELECT 5,'502',0,'',65,'Não','Araxá','planilha 17-21/08' WHERE EXISTS (SELECT 1 FROM dim_rotas WHERE codigo = '502') ON CONFLICT (dia_semana, rota_codigo, ordem) DO NOTHING;
INSERT INTO programacao_modelo (dia_semana, rota_codigo, ordem, tipo_operacao, qtd_entregas, paletizada, observacoes, criado_por) SELECT 5,'503',0,'',48,'Não','Patrocínio','planilha 17-21/08' WHERE EXISTS (SELECT 1 FROM dim_rotas WHERE codigo = '503') ON CONFLICT (dia_semana, rota_codigo, ordem) DO NOTHING;
INSERT INTO programacao_modelo (dia_semana, rota_codigo, ordem, tipo_operacao, qtd_entregas, paletizada, observacoes, criado_por) SELECT 5,'509',0,'',7,'Sim','ABC - Centro Oeste','planilha 17-21/08' WHERE EXISTS (SELECT 1 FROM dim_rotas WHERE codigo = '509') ON CONFLICT (dia_semana, rota_codigo, ordem) DO NOTHING;


-- NENHUMA LINHA DERRUBA A ATUALIZAÇÃO DO SERVIDOR.
--
-- Cada INSERT acima é condicionado a `EXISTS (SELECT 1 FROM dim_rotas ...)`.
-- O painel de produção tem MAIS rotas cadastradas que a base descartável em
-- que este arquivo foi montado; se mesmo assim algum código não existir lá,
-- aquela linha é PULADA em vez de abortar a migração inteira e deixar o
-- servidor parado numa versão antiga.
--
-- Pular calado seria ruim, então a contagem por dia sai no log do
-- atualizar.sh: dia curto na lista abaixo = código que falta cadastrar.
DO $$
DECLARE r RECORD;
BEGIN
  RAISE NOTICE 'Modelo da semana gravado:';
  FOR r IN
    SELECT dia_semana, count(*) AS n FROM programacao_modelo
     WHERE ativo GROUP BY dia_semana ORDER BY dia_semana
  LOOP
    RAISE NOTICE '  dia %: % rota(s)',
      (ARRAY['domingo','segunda','terça','quarta','quinta','sexta','sábado'])[r.dia_semana + 1], r.n;
  END LOOP;
END $$;

-- TOTAL: 101 linhas de modelo
--
-- FICARAM DE FORA (sem praça correspondente no cadastro):
--   1x  Hong Kong
--   1x  Minas Industrias
--   1x  Restaurante Gaucha
--   1x  Suinco - Leila
--   1x  Suinco - Maria Eduarda
