-- =====================================================================
-- 041 — O MODELO DA SEMANA PELAS PLANILHAS DO DONO (02/09/2026)
-- ---------------------------------------------------------------------
-- Fonte: as cinco planilhas "Programação da semana" enviadas pelo dono —
-- Segunda.xlsx, Terça.xlsx, Quarta.xlsx, Quinta.xlsx e Sexta.xlsx, aba
-- "Prog Carregamento". Pedido dele, com estas palavras:
--
--   "vou mandar um modelo de programacao e preciso que voce aplique ela
--    aos modelos de programacao do dia, exatamente do jeito que eu vou
--    mandar, substituindo o jeito e a sequencia que está la seguindo
--    fielmente estes modelos enviados"
--
-- O QUE ESTA MIGRAÇÃO FAZ: apaga o modelo atual e escreve as 80 linhas
-- das planilhas, na ordem em que elas aparecem na folha — de cima para
-- baixo, uma por linha.
--
-- A SEQUÊNCIA É A POSIÇÃO NA FOLHA, e não o número da primeira coluna.
-- Aquela coluna vem inconsistente: Terça começa no 3 e repete o 3 e o 18;
-- Quinta repete o 5 três vezes; Quarta não tem número nenhum. A ordem que
-- a operação enxerga é a de cima para baixo, e é essa que foi gravada.
-- Antes desta migração o campo `ordem` era quase todo zero — por isso a
-- sequência na tela parecia aleatória.
--
-- NENHUM CÓDIGO DE ROTA FOI INVENTADO. A planilha traz PRAÇA +
-- TRANSPORTADORA numa célula só ("Belo Horizonte - RP Express"); o
-- cadastro guarda a praça ("510 Belo Horizonte"). Cada um dos 80 nomes
-- casou com um código que já existia, quase todos pelo apelido que a
-- migração 033 já tinha gravado. A única sem precedente —
-- "Supermercado BH - Contagem" — ficou parada até o dono confirmar por
-- escrito que é a 510.
--
-- GRAFIA CORRIGIDA para o nome que o sistema já usa, decisão do dono:
-- Fioresta→Floresta, Logísitca→Logística, Goias→Goiás, Sao→São, e o
-- espaço duplo de "Total  Service". A rota é a mesma; o que muda é a
-- escrita que aparece na tela. Sem isso a mesma rota apareceria de dois
-- jeitos dependendo do dia, e quem buscasse por um não acharia o outro.
--
-- O QUE NÃO ENTROU, e o motivo:
--
--   · PERFIL DO VEÍCULO (3/4, Truck, Bitruck, Carreta). O modelo não tem
--     coluna para isso, e só Segunda e Terça vêm preenchidas. Decisão do
--     dono: deixar de fora por enquanto, em vez de criar coluna que
--     nasceria vazia em três dias de cinco.
--
--   · QTD. DE ENTREGAS. As planilhas vêm com a coluna em branco. O valor
--     antigo veio da semana de 17 a 21/08 (migração 033) — é a estimativa
--     de uma semana específica, e carregá-la para um modelo novo seria
--     mostrar número velho como se fosse o de agora.
--
-- SEM ESTA MIGRAÇÃO: o modelo da semana continua o antigo, das planilhas de
-- 17 a 21/08 (migração 033) — 100 linhas, com a sequência quase toda em zero
-- e por isso fora de ordem na tela. Nada quebra e nada dá erro: a Montagem
-- do Dia monta normalmente, só que pelo modelo velho, e a sequência que o
-- dono mandou não aparece. O painel novo não depende de coluna nenhuma que
-- esta migração crie — ela só troca DADO.
--
-- O QUE FOI PRESERVADO: `tipo_operacao` (CROSS-DOCKING / ENTREGA DIRETA /
-- RET FRIGO). Ele não está nas planilhas, mas é propriedade da ROTA e não
-- da semana — e a regra da casa é que campo vazio não é ordem de apagar.
-- Onde a mesma praça já tinha um tipo definido para aquele dia, ele foi
-- mantido; nas linhas novas nasce em branco, para a Logística preencher.
-- =====================================================================

-- Guarda o que existe hoje, para reaproveitar o tipo de operação.
CREATE TEMP TABLE _modelo_antigo AS
  SELECT DISTINCT ON (dia_semana, rota_codigo) dia_semana, rota_codigo, tipo_operacao
    FROM programacao_modelo WHERE ativo AND tipo_operacao <> ''
   ORDER BY dia_semana, rota_codigo, ordem;

DELETE FROM programacao_modelo;

-- segunda — 13 linhas
INSERT INTO programacao_modelo (dia_semana, rota_codigo, ordem, tipo_operacao, paletizada, apelido_rota, observacoes, criado_por) SELECT 1,'500',1,COALESCE((SELECT tipo_operacao FROM _modelo_antigo a WHERE a.dia_semana=1 AND a.rota_codigo='500'),''),'Não','Patos de Minas','planilha da semana 02/09','planilha do dono' WHERE EXISTS (SELECT 1 FROM dim_rotas WHERE codigo = '500') ON CONFLICT (dia_semana, rota_codigo, ordem) DO NOTHING;
INSERT INTO programacao_modelo (dia_semana, rota_codigo, ordem, tipo_operacao, paletizada, apelido_rota, observacoes, criado_por) SELECT 1,'500',2,COALESCE((SELECT tipo_operacao FROM _modelo_antigo a WHERE a.dia_semana=1 AND a.rota_codigo='500'),''),'Não','Patos de Minas','planilha da semana 02/09','planilha do dono' WHERE EXISTS (SELECT 1 FROM dim_rotas WHERE codigo = '500') ON CONFLICT (dia_semana, rota_codigo, ordem) DO NOTHING;
INSERT INTO programacao_modelo (dia_semana, rota_codigo, ordem, tipo_operacao, paletizada, apelido_rota, observacoes, criado_por) SELECT 1,'501',3,COALESCE((SELECT tipo_operacao FROM _modelo_antigo a WHERE a.dia_semana=1 AND a.rota_codigo='501'),''),'Não','São Gotardo','planilha da semana 02/09','planilha do dono' WHERE EXISTS (SELECT 1 FROM dim_rotas WHERE codigo = '501') ON CONFLICT (dia_semana, rota_codigo, ordem) DO NOTHING;
INSERT INTO programacao_modelo (dia_semana, rota_codigo, ordem, tipo_operacao, paletizada, apelido_rota, observacoes, criado_por) SELECT 1,'501',4,COALESCE((SELECT tipo_operacao FROM _modelo_antigo a WHERE a.dia_semana=1 AND a.rota_codigo='501'),''),'Não','São Gotardo','planilha da semana 02/09','planilha do dono' WHERE EXISTS (SELECT 1 FROM dim_rotas WHERE codigo = '501') ON CONFLICT (dia_semana, rota_codigo, ordem) DO NOTHING;
INSERT INTO programacao_modelo (dia_semana, rota_codigo, ordem, tipo_operacao, paletizada, apelido_rota, observacoes, criado_por) SELECT 1,'505',5,COALESCE((SELECT tipo_operacao FROM _modelo_antigo a WHERE a.dia_semana=1 AND a.rota_codigo='505'),''),'Não','Triângulo Mineiro - Total Service','planilha da semana 02/09','planilha do dono' WHERE EXISTS (SELECT 1 FROM dim_rotas WHERE codigo = '505') ON CONFLICT (dia_semana, rota_codigo, ordem) DO NOTHING;
INSERT INTO programacao_modelo (dia_semana, rota_codigo, ordem, tipo_operacao, paletizada, apelido_rota, observacoes, criado_por) SELECT 1,'521',6,COALESCE((SELECT tipo_operacao FROM _modelo_antigo a WHERE a.dia_semana=1 AND a.rota_codigo='521'),''),'Sim','Ribeirão Preto - Cargo Frio','planilha da semana 02/09','planilha do dono' WHERE EXISTS (SELECT 1 FROM dim_rotas WHERE codigo = '521') ON CONFLICT (dia_semana, rota_codigo, ordem) DO NOTHING;
INSERT INTO programacao_modelo (dia_semana, rota_codigo, ordem, tipo_operacao, paletizada, apelido_rota, observacoes, criado_por) SELECT 1,'538',7,COALESCE((SELECT tipo_operacao FROM _modelo_antigo a WHERE a.dia_semana=1 AND a.rota_codigo='538'),''),'Sim','Marília - Cargo Frio','planilha da semana 02/09','planilha do dono' WHERE EXISTS (SELECT 1 FROM dim_rotas WHERE codigo = '538') ON CONFLICT (dia_semana, rota_codigo, ordem) DO NOTHING;
INSERT INTO programacao_modelo (dia_semana, rota_codigo, ordem, tipo_operacao, paletizada, apelido_rota, observacoes, criado_por) SELECT 1,'510',8,COALESCE((SELECT tipo_operacao FROM _modelo_antigo a WHERE a.dia_semana=1 AND a.rota_codigo='510'),''),'Sim','Belo Horizonte - RP Express','planilha da semana 02/09','planilha do dono' WHERE EXISTS (SELECT 1 FROM dim_rotas WHERE codigo = '510') ON CONFLICT (dia_semana, rota_codigo, ordem) DO NOTHING;
INSERT INTO programacao_modelo (dia_semana, rota_codigo, ordem, tipo_operacao, paletizada, apelido_rota, observacoes, criado_por) SELECT 1,'519',9,COALESCE((SELECT tipo_operacao FROM _modelo_antigo a WHERE a.dia_semana=1 AND a.rota_codigo='519'),''),'Sim','Brasília - Versatto','planilha da semana 02/09','planilha do dono' WHERE EXISTS (SELECT 1 FROM dim_rotas WHERE codigo = '519') ON CONFLICT (dia_semana, rota_codigo, ordem) DO NOTHING;
INSERT INTO programacao_modelo (dia_semana, rota_codigo, ordem, tipo_operacao, paletizada, apelido_rota, observacoes, criado_por) SELECT 1,'517',10,COALESCE((SELECT tipo_operacao FROM _modelo_antigo a WHERE a.dia_semana=1 AND a.rota_codigo='517'),''),'Sim','Rio de Janeiro - Ômega X','planilha da semana 02/09','planilha do dono' WHERE EXISTS (SELECT 1 FROM dim_rotas WHERE codigo = '517') ON CONFLICT (dia_semana, rota_codigo, ordem) DO NOTHING;
INSERT INTO programacao_modelo (dia_semana, rota_codigo, ordem, tipo_operacao, paletizada, apelido_rota, observacoes, criado_por) SELECT 1,'517',11,COALESCE((SELECT tipo_operacao FROM _modelo_antigo a WHERE a.dia_semana=1 AND a.rota_codigo='517'),''),'Sim','Rio de Janeiro - Ômega X','planilha da semana 02/09','planilha do dono' WHERE EXISTS (SELECT 1 FROM dim_rotas WHERE codigo = '517') ON CONFLICT (dia_semana, rota_codigo, ordem) DO NOTHING;
INSERT INTO programacao_modelo (dia_semana, rota_codigo, ordem, tipo_operacao, paletizada, apelido_rota, observacoes, criado_por) SELECT 1,'525',12,COALESCE((SELECT tipo_operacao FROM _modelo_antigo a WHERE a.dia_semana=1 AND a.rota_codigo='525'),''),'Sim','Bahia Capital - LogMaster','planilha da semana 02/09','planilha do dono' WHERE EXISTS (SELECT 1 FROM dim_rotas WHERE codigo = '525') ON CONFLICT (dia_semana, rota_codigo, ordem) DO NOTHING;
INSERT INTO programacao_modelo (dia_semana, rota_codigo, ordem, tipo_operacao, paletizada, apelido_rota, observacoes, criado_por) SELECT 1,'525',13,COALESCE((SELECT tipo_operacao FROM _modelo_antigo a WHERE a.dia_semana=1 AND a.rota_codigo='525'),''),'Sim','Bahia Capital - LogMaster','planilha da semana 02/09','planilha do dono' WHERE EXISTS (SELECT 1 FROM dim_rotas WHERE codigo = '525') ON CONFLICT (dia_semana, rota_codigo, ordem) DO NOTHING;

-- terça — 21 linhas
INSERT INTO programacao_modelo (dia_semana, rota_codigo, ordem, tipo_operacao, paletizada, apelido_rota, observacoes, criado_por) SELECT 2,'509',1,COALESCE((SELECT tipo_operacao FROM _modelo_antigo a WHERE a.dia_semana=2 AND a.rota_codigo='509'),''),'Sim','Centro-Oeste 6 Rotas','planilha da semana 02/09','planilha do dono' WHERE EXISTS (SELECT 1 FROM dim_rotas WHERE codigo = '509') ON CONFLICT (dia_semana, rota_codigo, ordem) DO NOTHING;
INSERT INTO programacao_modelo (dia_semana, rota_codigo, ordem, tipo_operacao, paletizada, apelido_rota, observacoes, criado_por) SELECT 2,'517',2,COALESCE((SELECT tipo_operacao FROM _modelo_antigo a WHERE a.dia_semana=2 AND a.rota_codigo='517'),''),'Sim','Floresta RJ','planilha da semana 02/09','planilha do dono' WHERE EXISTS (SELECT 1 FROM dim_rotas WHERE codigo = '517') ON CONFLICT (dia_semana, rota_codigo, ordem) DO NOTHING;
INSERT INTO programacao_modelo (dia_semana, rota_codigo, ordem, tipo_operacao, paletizada, apelido_rota, observacoes, criado_por) SELECT 2,'500',3,COALESCE((SELECT tipo_operacao FROM _modelo_antigo a WHERE a.dia_semana=2 AND a.rota_codigo='500'),''),'Não','Patos de Minas','planilha da semana 02/09','planilha do dono' WHERE EXISTS (SELECT 1 FROM dim_rotas WHERE codigo = '500') ON CONFLICT (dia_semana, rota_codigo, ordem) DO NOTHING;
INSERT INTO programacao_modelo (dia_semana, rota_codigo, ordem, tipo_operacao, paletizada, apelido_rota, observacoes, criado_por) SELECT 2,'500',4,COALESCE((SELECT tipo_operacao FROM _modelo_antigo a WHERE a.dia_semana=2 AND a.rota_codigo='500'),''),'Não','Patos de Minas','planilha da semana 02/09','planilha do dono' WHERE EXISTS (SELECT 1 FROM dim_rotas WHERE codigo = '500') ON CONFLICT (dia_semana, rota_codigo, ordem) DO NOTHING;
INSERT INTO programacao_modelo (dia_semana, rota_codigo, ordem, tipo_operacao, paletizada, apelido_rota, observacoes, criado_por) SELECT 2,'536',5,COALESCE((SELECT tipo_operacao FROM _modelo_antigo a WHERE a.dia_semana=2 AND a.rota_codigo='536'),''),'Sim','Goiás - AG Sestini','planilha da semana 02/09','planilha do dono' WHERE EXISTS (SELECT 1 FROM dim_rotas WHERE codigo = '536') ON CONFLICT (dia_semana, rota_codigo, ordem) DO NOTHING;
INSERT INTO programacao_modelo (dia_semana, rota_codigo, ordem, tipo_operacao, paletizada, apelido_rota, observacoes, criado_por) SELECT 2,'522',6,COALESCE((SELECT tipo_operacao FROM _modelo_antigo a WHERE a.dia_semana=2 AND a.rota_codigo='522'),''),'Sim','SP Capital - SPM Log','planilha da semana 02/09','planilha do dono' WHERE EXISTS (SELECT 1 FROM dim_rotas WHERE codigo = '522') ON CONFLICT (dia_semana, rota_codigo, ordem) DO NOTHING;
INSERT INTO programacao_modelo (dia_semana, rota_codigo, ordem, tipo_operacao, paletizada, apelido_rota, observacoes, criado_por) SELECT 2,'524',7,COALESCE((SELECT tipo_operacao FROM _modelo_antigo a WHERE a.dia_semana=2 AND a.rota_codigo='524'),''),'Sim','Zona da Mata - BSF Logística','planilha da semana 02/09','planilha do dono' WHERE EXISTS (SELECT 1 FROM dim_rotas WHERE codigo = '524') ON CONFLICT (dia_semana, rota_codigo, ordem) DO NOTHING;
INSERT INTO programacao_modelo (dia_semana, rota_codigo, ordem, tipo_operacao, paletizada, apelido_rota, observacoes, criado_por) SELECT 2,'516',8,COALESCE((SELECT tipo_operacao FROM _modelo_antigo a WHERE a.dia_semana=2 AND a.rota_codigo='516'),''),'Sim','Montes Claros - Mult Service','planilha da semana 02/09','planilha do dono' WHERE EXISTS (SELECT 1 FROM dim_rotas WHERE codigo = '516') ON CONFLICT (dia_semana, rota_codigo, ordem) DO NOTHING;
INSERT INTO programacao_modelo (dia_semana, rota_codigo, ordem, tipo_operacao, paletizada, apelido_rota, observacoes, criado_por) SELECT 2,'505',9,COALESCE((SELECT tipo_operacao FROM _modelo_antigo a WHERE a.dia_semana=2 AND a.rota_codigo='505'),''),'Sim','Triângulo Mineiro - Total Service','planilha da semana 02/09','planilha do dono' WHERE EXISTS (SELECT 1 FROM dim_rotas WHERE codigo = '505') ON CONFLICT (dia_semana, rota_codigo, ordem) DO NOTHING;
INSERT INTO programacao_modelo (dia_semana, rota_codigo, ordem, tipo_operacao, paletizada, apelido_rota, observacoes, criado_por) SELECT 2,'512',10,COALESCE((SELECT tipo_operacao FROM _modelo_antigo a WHERE a.dia_semana=2 AND a.rota_codigo='512'),''),'Sim','Varginha - Brasfrios','planilha da semana 02/09','planilha do dono' WHERE EXISTS (SELECT 1 FROM dim_rotas WHERE codigo = '512') ON CONFLICT (dia_semana, rota_codigo, ordem) DO NOTHING;
INSERT INTO programacao_modelo (dia_semana, rota_codigo, ordem, tipo_operacao, paletizada, apelido_rota, observacoes, criado_por) SELECT 2,'513',11,COALESCE((SELECT tipo_operacao FROM _modelo_antigo a WHERE a.dia_semana=2 AND a.rota_codigo='513'),''),'Sim','Passos - Maxfrios','planilha da semana 02/09','planilha do dono' WHERE EXISTS (SELECT 1 FROM dim_rotas WHERE codigo = '513') ON CONFLICT (dia_semana, rota_codigo, ordem) DO NOTHING;
INSERT INTO programacao_modelo (dia_semana, rota_codigo, ordem, tipo_operacao, paletizada, apelido_rota, observacoes, criado_por) SELECT 2,'517',12,COALESCE((SELECT tipo_operacao FROM _modelo_antigo a WHERE a.dia_semana=2 AND a.rota_codigo='517'),''),'Sim','Rio de Janeiro - Ômega X','planilha da semana 02/09','planilha do dono' WHERE EXISTS (SELECT 1 FROM dim_rotas WHERE codigo = '517') ON CONFLICT (dia_semana, rota_codigo, ordem) DO NOTHING;
INSERT INTO programacao_modelo (dia_semana, rota_codigo, ordem, tipo_operacao, paletizada, apelido_rota, observacoes, criado_por) SELECT 2,'517',13,COALESCE((SELECT tipo_operacao FROM _modelo_antigo a WHERE a.dia_semana=2 AND a.rota_codigo='517'),''),'Sim','Rio de Janeiro - Ômega X','planilha da semana 02/09','planilha do dono' WHERE EXISTS (SELECT 1 FROM dim_rotas WHERE codigo = '517') ON CONFLICT (dia_semana, rota_codigo, ordem) DO NOTHING;
INSERT INTO programacao_modelo (dia_semana, rota_codigo, ordem, tipo_operacao, paletizada, apelido_rota, observacoes, criado_por) SELECT 2,'504',14,COALESCE((SELECT tipo_operacao FROM _modelo_antigo a WHERE a.dia_semana=2 AND a.rota_codigo='504'),''),'Não','Arinos / Buritis','planilha da semana 02/09','planilha do dono' WHERE EXISTS (SELECT 1 FROM dim_rotas WHERE codigo = '504') ON CONFLICT (dia_semana, rota_codigo, ordem) DO NOTHING;
INSERT INTO programacao_modelo (dia_semana, rota_codigo, ordem, tipo_operacao, paletizada, apelido_rota, observacoes, criado_por) SELECT 2,'504',15,COALESCE((SELECT tipo_operacao FROM _modelo_antigo a WHERE a.dia_semana=2 AND a.rota_codigo='504'),''),'Não','Riachinho','planilha da semana 02/09','planilha do dono' WHERE EXISTS (SELECT 1 FROM dim_rotas WHERE codigo = '504') ON CONFLICT (dia_semana, rota_codigo, ordem) DO NOTHING;
INSERT INTO programacao_modelo (dia_semana, rota_codigo, ordem, tipo_operacao, paletizada, apelido_rota, observacoes, criado_por) SELECT 2,'504',16,COALESCE((SELECT tipo_operacao FROM _modelo_antigo a WHERE a.dia_semana=2 AND a.rota_codigo='504'),''),'Não','João Pinheiro','planilha da semana 02/09','planilha do dono' WHERE EXISTS (SELECT 1 FROM dim_rotas WHERE codigo = '504') ON CONFLICT (dia_semana, rota_codigo, ordem) DO NOTHING;
INSERT INTO programacao_modelo (dia_semana, rota_codigo, ordem, tipo_operacao, paletizada, apelido_rota, observacoes, criado_por) SELECT 2,'504',17,COALESCE((SELECT tipo_operacao FROM _modelo_antigo a WHERE a.dia_semana=2 AND a.rota_codigo='504'),''),'Não','Paracatu','planilha da semana 02/09','planilha do dono' WHERE EXISTS (SELECT 1 FROM dim_rotas WHERE codigo = '504') ON CONFLICT (dia_semana, rota_codigo, ordem) DO NOTHING;
INSERT INTO programacao_modelo (dia_semana, rota_codigo, ordem, tipo_operacao, paletizada, apelido_rota, observacoes, criado_por) SELECT 2,'504',18,COALESCE((SELECT tipo_operacao FROM _modelo_antigo a WHERE a.dia_semana=2 AND a.rota_codigo='504'),''),'Não','Unaí','planilha da semana 02/09','planilha do dono' WHERE EXISTS (SELECT 1 FROM dim_rotas WHERE codigo = '504') ON CONFLICT (dia_semana, rota_codigo, ordem) DO NOTHING;
INSERT INTO programacao_modelo (dia_semana, rota_codigo, ordem, tipo_operacao, paletizada, apelido_rota, observacoes, criado_por) SELECT 2,'502',19,COALESCE((SELECT tipo_operacao FROM _modelo_antigo a WHERE a.dia_semana=2 AND a.rota_codigo='502'),''),'Não','Araxá','planilha da semana 02/09','planilha do dono' WHERE EXISTS (SELECT 1 FROM dim_rotas WHERE codigo = '502') ON CONFLICT (dia_semana, rota_codigo, ordem) DO NOTHING;
INSERT INTO programacao_modelo (dia_semana, rota_codigo, ordem, tipo_operacao, paletizada, apelido_rota, observacoes, criado_por) SELECT 2,'503',20,COALESCE((SELECT tipo_operacao FROM _modelo_antigo a WHERE a.dia_semana=2 AND a.rota_codigo='503'),''),'Não','Patrocínio','planilha da semana 02/09','planilha do dono' WHERE EXISTS (SELECT 1 FROM dim_rotas WHERE codigo = '503') ON CONFLICT (dia_semana, rota_codigo, ordem) DO NOTHING;
INSERT INTO programacao_modelo (dia_semana, rota_codigo, ordem, tipo_operacao, paletizada, apelido_rota, observacoes, criado_por) SELECT 2,'503',21,COALESCE((SELECT tipo_operacao FROM _modelo_antigo a WHERE a.dia_semana=2 AND a.rota_codigo='503'),''),'Não','Coromandel','planilha da semana 02/09','planilha do dono' WHERE EXISTS (SELECT 1 FROM dim_rotas WHERE codigo = '503') ON CONFLICT (dia_semana, rota_codigo, ordem) DO NOTHING;

-- quarta — 9 linhas
INSERT INTO programacao_modelo (dia_semana, rota_codigo, ordem, tipo_operacao, paletizada, apelido_rota, observacoes, criado_por) SELECT 3,'500',1,COALESCE((SELECT tipo_operacao FROM _modelo_antigo a WHERE a.dia_semana=3 AND a.rota_codigo='500'),''),'','Patos de Minas','planilha da semana 02/09','planilha do dono' WHERE EXISTS (SELECT 1 FROM dim_rotas WHERE codigo = '500') ON CONFLICT (dia_semana, rota_codigo, ordem) DO NOTHING;
INSERT INTO programacao_modelo (dia_semana, rota_codigo, ordem, tipo_operacao, paletizada, apelido_rota, observacoes, criado_por) SELECT 3,'500',2,COALESCE((SELECT tipo_operacao FROM _modelo_antigo a WHERE a.dia_semana=3 AND a.rota_codigo='500'),''),'','Patos de Minas','planilha da semana 02/09','planilha do dono' WHERE EXISTS (SELECT 1 FROM dim_rotas WHERE codigo = '500') ON CONFLICT (dia_semana, rota_codigo, ordem) DO NOTHING;
INSERT INTO programacao_modelo (dia_semana, rota_codigo, ordem, tipo_operacao, paletizada, apelido_rota, observacoes, criado_por) SELECT 3,'501',3,COALESCE((SELECT tipo_operacao FROM _modelo_antigo a WHERE a.dia_semana=3 AND a.rota_codigo='501'),''),'','São Gotardo','planilha da semana 02/09','planilha do dono' WHERE EXISTS (SELECT 1 FROM dim_rotas WHERE codigo = '501') ON CONFLICT (dia_semana, rota_codigo, ordem) DO NOTHING;
INSERT INTO programacao_modelo (dia_semana, rota_codigo, ordem, tipo_operacao, paletizada, apelido_rota, observacoes, criado_por) SELECT 3,'501',4,COALESCE((SELECT tipo_operacao FROM _modelo_antigo a WHERE a.dia_semana=3 AND a.rota_codigo='501'),''),'','São Gotardo','planilha da semana 02/09','planilha do dono' WHERE EXISTS (SELECT 1 FROM dim_rotas WHERE codigo = '501') ON CONFLICT (dia_semana, rota_codigo, ordem) DO NOTHING;
INSERT INTO programacao_modelo (dia_semana, rota_codigo, ordem, tipo_operacao, paletizada, apelido_rota, observacoes, criado_por) SELECT 3,'517',5,COALESCE((SELECT tipo_operacao FROM _modelo_antigo a WHERE a.dia_semana=3 AND a.rota_codigo='517'),''),'','Rio de Janeiro - Ômega X','planilha da semana 02/09','planilha do dono' WHERE EXISTS (SELECT 1 FROM dim_rotas WHERE codigo = '517') ON CONFLICT (dia_semana, rota_codigo, ordem) DO NOTHING;
INSERT INTO programacao_modelo (dia_semana, rota_codigo, ordem, tipo_operacao, paletizada, apelido_rota, observacoes, criado_por) SELECT 3,'518',6,COALESCE((SELECT tipo_operacao FROM _modelo_antigo a WHERE a.dia_semana=3 AND a.rota_codigo='518'),''),'','Rio de Janeiro - Kanejo','planilha da semana 02/09','planilha do dono' WHERE EXISTS (SELECT 1 FROM dim_rotas WHERE codigo = '518') ON CONFLICT (dia_semana, rota_codigo, ordem) DO NOTHING;
INSERT INTO programacao_modelo (dia_semana, rota_codigo, ordem, tipo_operacao, paletizada, apelido_rota, observacoes, criado_por) SELECT 3,'510',7,COALESCE((SELECT tipo_operacao FROM _modelo_antigo a WHERE a.dia_semana=3 AND a.rota_codigo='510'),''),'','Supermercado BH - Contagem','planilha da semana 02/09','planilha do dono' WHERE EXISTS (SELECT 1 FROM dim_rotas WHERE codigo = '510') ON CONFLICT (dia_semana, rota_codigo, ordem) DO NOTHING;
INSERT INTO programacao_modelo (dia_semana, rota_codigo, ordem, tipo_operacao, paletizada, apelido_rota, observacoes, criado_por) SELECT 3,'510',8,COALESCE((SELECT tipo_operacao FROM _modelo_antigo a WHERE a.dia_semana=3 AND a.rota_codigo='510'),''),'','Belo Horizonte - RP Express','planilha da semana 02/09','planilha do dono' WHERE EXISTS (SELECT 1 FROM dim_rotas WHERE codigo = '510') ON CONFLICT (dia_semana, rota_codigo, ordem) DO NOTHING;
INSERT INTO programacao_modelo (dia_semana, rota_codigo, ordem, tipo_operacao, paletizada, apelido_rota, observacoes, criado_por) SELECT 3,'519',9,COALESCE((SELECT tipo_operacao FROM _modelo_antigo a WHERE a.dia_semana=3 AND a.rota_codigo='519'),''),'','Brasília - Versatto','planilha da semana 02/09','planilha do dono' WHERE EXISTS (SELECT 1 FROM dim_rotas WHERE codigo = '519') ON CONFLICT (dia_semana, rota_codigo, ordem) DO NOTHING;

-- quinta — 12 linhas
INSERT INTO programacao_modelo (dia_semana, rota_codigo, ordem, tipo_operacao, paletizada, apelido_rota, observacoes, criado_por) SELECT 4,'500',1,COALESCE((SELECT tipo_operacao FROM _modelo_antigo a WHERE a.dia_semana=4 AND a.rota_codigo='500'),''),'','Patos de Minas','planilha da semana 02/09','planilha do dono' WHERE EXISTS (SELECT 1 FROM dim_rotas WHERE codigo = '500') ON CONFLICT (dia_semana, rota_codigo, ordem) DO NOTHING;
INSERT INTO programacao_modelo (dia_semana, rota_codigo, ordem, tipo_operacao, paletizada, apelido_rota, observacoes, criado_por) SELECT 4,'500',2,COALESCE((SELECT tipo_operacao FROM _modelo_antigo a WHERE a.dia_semana=4 AND a.rota_codigo='500'),''),'','Patos de Minas','planilha da semana 02/09','planilha do dono' WHERE EXISTS (SELECT 1 FROM dim_rotas WHERE codigo = '500') ON CONFLICT (dia_semana, rota_codigo, ordem) DO NOTHING;
INSERT INTO programacao_modelo (dia_semana, rota_codigo, ordem, tipo_operacao, paletizada, apelido_rota, observacoes, criado_por) SELECT 4,'501',3,COALESCE((SELECT tipo_operacao FROM _modelo_antigo a WHERE a.dia_semana=4 AND a.rota_codigo='501'),''),'','São Gotardo','planilha da semana 02/09','planilha do dono' WHERE EXISTS (SELECT 1 FROM dim_rotas WHERE codigo = '501') ON CONFLICT (dia_semana, rota_codigo, ordem) DO NOTHING;
INSERT INTO programacao_modelo (dia_semana, rota_codigo, ordem, tipo_operacao, paletizada, apelido_rota, observacoes, criado_por) SELECT 4,'501',4,COALESCE((SELECT tipo_operacao FROM _modelo_antigo a WHERE a.dia_semana=4 AND a.rota_codigo='501'),''),'','São Gotardo','planilha da semana 02/09','planilha do dono' WHERE EXISTS (SELECT 1 FROM dim_rotas WHERE codigo = '501') ON CONFLICT (dia_semana, rota_codigo, ordem) DO NOTHING;
INSERT INTO programacao_modelo (dia_semana, rota_codigo, ordem, tipo_operacao, paletizada, apelido_rota, observacoes, criado_por) SELECT 4,'521',5,COALESCE((SELECT tipo_operacao FROM _modelo_antigo a WHERE a.dia_semana=4 AND a.rota_codigo='521'),''),'','Ribeirão Preto - Cargo Frio','planilha da semana 02/09','planilha do dono' WHERE EXISTS (SELECT 1 FROM dim_rotas WHERE codigo = '521') ON CONFLICT (dia_semana, rota_codigo, ordem) DO NOTHING;
INSERT INTO programacao_modelo (dia_semana, rota_codigo, ordem, tipo_operacao, paletizada, apelido_rota, observacoes, criado_por) SELECT 4,'538',6,COALESCE((SELECT tipo_operacao FROM _modelo_antigo a WHERE a.dia_semana=4 AND a.rota_codigo='538'),''),'','Marília - Cargo Frio','planilha da semana 02/09','planilha do dono' WHERE EXISTS (SELECT 1 FROM dim_rotas WHERE codigo = '538') ON CONFLICT (dia_semana, rota_codigo, ordem) DO NOTHING;
INSERT INTO programacao_modelo (dia_semana, rota_codigo, ordem, tipo_operacao, paletizada, apelido_rota, observacoes, criado_por) SELECT 4,'517',7,COALESCE((SELECT tipo_operacao FROM _modelo_antigo a WHERE a.dia_semana=4 AND a.rota_codigo='517'),''),'','Rio de Janeiro - Ômega X','planilha da semana 02/09','planilha do dono' WHERE EXISTS (SELECT 1 FROM dim_rotas WHERE codigo = '517') ON CONFLICT (dia_semana, rota_codigo, ordem) DO NOTHING;
INSERT INTO programacao_modelo (dia_semana, rota_codigo, ordem, tipo_operacao, paletizada, apelido_rota, observacoes, criado_por) SELECT 4,'517',8,COALESCE((SELECT tipo_operacao FROM _modelo_antigo a WHERE a.dia_semana=4 AND a.rota_codigo='517'),''),'','Rio de Janeiro - Ômega X','planilha da semana 02/09','planilha do dono' WHERE EXISTS (SELECT 1 FROM dim_rotas WHERE codigo = '517') ON CONFLICT (dia_semana, rota_codigo, ordem) DO NOTHING;
INSERT INTO programacao_modelo (dia_semana, rota_codigo, ordem, tipo_operacao, paletizada, apelido_rota, observacoes, criado_por) SELECT 4,'525',9,COALESCE((SELECT tipo_operacao FROM _modelo_antigo a WHERE a.dia_semana=4 AND a.rota_codigo='525'),''),'','Bahia Capital - LogMaster','planilha da semana 02/09','planilha do dono' WHERE EXISTS (SELECT 1 FROM dim_rotas WHERE codigo = '525') ON CONFLICT (dia_semana, rota_codigo, ordem) DO NOTHING;
INSERT INTO programacao_modelo (dia_semana, rota_codigo, ordem, tipo_operacao, paletizada, apelido_rota, observacoes, criado_por) SELECT 4,'525',10,COALESCE((SELECT tipo_operacao FROM _modelo_antigo a WHERE a.dia_semana=4 AND a.rota_codigo='525'),''),'','Bahia Capital - LogMaster','planilha da semana 02/09','planilha do dono' WHERE EXISTS (SELECT 1 FROM dim_rotas WHERE codigo = '525') ON CONFLICT (dia_semana, rota_codigo, ordem) DO NOTHING;
INSERT INTO programacao_modelo (dia_semana, rota_codigo, ordem, tipo_operacao, paletizada, apelido_rota, observacoes, criado_por) SELECT 4,'532',11,COALESCE((SELECT tipo_operacao FROM _modelo_antigo a WHERE a.dia_semana=4 AND a.rota_codigo='532'),''),'','Bahia Interior - TransVieira','planilha da semana 02/09','planilha do dono' WHERE EXISTS (SELECT 1 FROM dim_rotas WHERE codigo = '532') ON CONFLICT (dia_semana, rota_codigo, ordem) DO NOTHING;
INSERT INTO programacao_modelo (dia_semana, rota_codigo, ordem, tipo_operacao, paletizada, apelido_rota, observacoes, criado_por) SELECT 4,'532',12,COALESCE((SELECT tipo_operacao FROM _modelo_antigo a WHERE a.dia_semana=4 AND a.rota_codigo='532'),''),'','Bahia Interior - TransVieira','planilha da semana 02/09','planilha do dono' WHERE EXISTS (SELECT 1 FROM dim_rotas WHERE codigo = '532') ON CONFLICT (dia_semana, rota_codigo, ordem) DO NOTHING;

-- sexta — 25 linhas
INSERT INTO programacao_modelo (dia_semana, rota_codigo, ordem, tipo_operacao, paletizada, apelido_rota, observacoes, criado_por) SELECT 5,'517',1,COALESCE((SELECT tipo_operacao FROM _modelo_antigo a WHERE a.dia_semana=5 AND a.rota_codigo='517'),''),'','Rio de Janeiro - Ômega X','planilha da semana 02/09','planilha do dono' WHERE EXISTS (SELECT 1 FROM dim_rotas WHERE codigo = '517') ON CONFLICT (dia_semana, rota_codigo, ordem) DO NOTHING;
INSERT INTO programacao_modelo (dia_semana, rota_codigo, ordem, tipo_operacao, paletizada, apelido_rota, observacoes, criado_por) SELECT 5,'517',2,COALESCE((SELECT tipo_operacao FROM _modelo_antigo a WHERE a.dia_semana=5 AND a.rota_codigo='517'),''),'','Rio de Janeiro - Ômega X','planilha da semana 02/09','planilha do dono' WHERE EXISTS (SELECT 1 FROM dim_rotas WHERE codigo = '517') ON CONFLICT (dia_semana, rota_codigo, ordem) DO NOTHING;
INSERT INTO programacao_modelo (dia_semana, rota_codigo, ordem, tipo_operacao, paletizada, apelido_rota, observacoes, criado_por) SELECT 5,'516',3,COALESCE((SELECT tipo_operacao FROM _modelo_antigo a WHERE a.dia_semana=5 AND a.rota_codigo='516'),''),'','Montes Claros - Total Service','planilha da semana 02/09','planilha do dono' WHERE EXISTS (SELECT 1 FROM dim_rotas WHERE codigo = '516') ON CONFLICT (dia_semana, rota_codigo, ordem) DO NOTHING;
INSERT INTO programacao_modelo (dia_semana, rota_codigo, ordem, tipo_operacao, paletizada, apelido_rota, observacoes, criado_por) SELECT 5,'516',4,COALESCE((SELECT tipo_operacao FROM _modelo_antigo a WHERE a.dia_semana=5 AND a.rota_codigo='516'),''),'','Montes Claros - Total Service','planilha da semana 02/09','planilha do dono' WHERE EXISTS (SELECT 1 FROM dim_rotas WHERE codigo = '516') ON CONFLICT (dia_semana, rota_codigo, ordem) DO NOTHING;
INSERT INTO programacao_modelo (dia_semana, rota_codigo, ordem, tipo_operacao, paletizada, apelido_rota, observacoes, criado_por) SELECT 5,'536',5,COALESCE((SELECT tipo_operacao FROM _modelo_antigo a WHERE a.dia_semana=5 AND a.rota_codigo='536'),''),'','Goiás - AG Sestini','planilha da semana 02/09','planilha do dono' WHERE EXISTS (SELECT 1 FROM dim_rotas WHERE codigo = '536') ON CONFLICT (dia_semana, rota_codigo, ordem) DO NOTHING;
INSERT INTO programacao_modelo (dia_semana, rota_codigo, ordem, tipo_operacao, paletizada, apelido_rota, observacoes, criado_por) SELECT 5,'519',6,COALESCE((SELECT tipo_operacao FROM _modelo_antigo a WHERE a.dia_semana=5 AND a.rota_codigo='519'),''),'','Brasília - Versatto','planilha da semana 02/09','planilha do dono' WHERE EXISTS (SELECT 1 FROM dim_rotas WHERE codigo = '519') ON CONFLICT (dia_semana, rota_codigo, ordem) DO NOTHING;
INSERT INTO programacao_modelo (dia_semana, rota_codigo, ordem, tipo_operacao, paletizada, apelido_rota, observacoes, criado_por) SELECT 5,'524',7,COALESCE((SELECT tipo_operacao FROM _modelo_antigo a WHERE a.dia_semana=5 AND a.rota_codigo='524'),''),'','Zona da Mata - BSF Logística','planilha da semana 02/09','planilha do dono' WHERE EXISTS (SELECT 1 FROM dim_rotas WHERE codigo = '524') ON CONFLICT (dia_semana, rota_codigo, ordem) DO NOTHING;
INSERT INTO programacao_modelo (dia_semana, rota_codigo, ordem, tipo_operacao, paletizada, apelido_rota, observacoes, criado_por) SELECT 5,'522',8,COALESCE((SELECT tipo_operacao FROM _modelo_antigo a WHERE a.dia_semana=5 AND a.rota_codigo='522'),''),'','Osasco - SPM Logística','planilha da semana 02/09','planilha do dono' WHERE EXISTS (SELECT 1 FROM dim_rotas WHERE codigo = '522') ON CONFLICT (dia_semana, rota_codigo, ordem) DO NOTHING;
INSERT INTO programacao_modelo (dia_semana, rota_codigo, ordem, tipo_operacao, paletizada, apelido_rota, observacoes, criado_por) SELECT 5,'505',9,COALESCE((SELECT tipo_operacao FROM _modelo_antigo a WHERE a.dia_semana=5 AND a.rota_codigo='505'),''),'','Triângulo Mineiro - Total Service','planilha da semana 02/09','planilha do dono' WHERE EXISTS (SELECT 1 FROM dim_rotas WHERE codigo = '505') ON CONFLICT (dia_semana, rota_codigo, ordem) DO NOTHING;
INSERT INTO programacao_modelo (dia_semana, rota_codigo, ordem, tipo_operacao, paletizada, apelido_rota, observacoes, criado_por) SELECT 5,'519',10,COALESCE((SELECT tipo_operacao FROM _modelo_antigo a WHERE a.dia_semana=5 AND a.rota_codigo='519'),''),'','Brasília - Pantanal','planilha da semana 02/09','planilha do dono' WHERE EXISTS (SELECT 1 FROM dim_rotas WHERE codigo = '519') ON CONFLICT (dia_semana, rota_codigo, ordem) DO NOTHING;
INSERT INTO programacao_modelo (dia_semana, rota_codigo, ordem, tipo_operacao, paletizada, apelido_rota, observacoes, criado_por) SELECT 5,'510',11,COALESCE((SELECT tipo_operacao FROM _modelo_antigo a WHERE a.dia_semana=5 AND a.rota_codigo='510'),''),'','Belo Horizonte - RP Express','planilha da semana 02/09','planilha do dono' WHERE EXISTS (SELECT 1 FROM dim_rotas WHERE codigo = '510') ON CONFLICT (dia_semana, rota_codigo, ordem) DO NOTHING;
INSERT INTO programacao_modelo (dia_semana, rota_codigo, ordem, tipo_operacao, paletizada, apelido_rota, observacoes, criado_por) SELECT 5,'512',12,COALESCE((SELECT tipo_operacao FROM _modelo_antigo a WHERE a.dia_semana=5 AND a.rota_codigo='512'),''),'','Varginha - Brasfrios','planilha da semana 02/09','planilha do dono' WHERE EXISTS (SELECT 1 FROM dim_rotas WHERE codigo = '512') ON CONFLICT (dia_semana, rota_codigo, ordem) DO NOTHING;
INSERT INTO programacao_modelo (dia_semana, rota_codigo, ordem, tipo_operacao, paletizada, apelido_rota, observacoes, criado_por) SELECT 5,'513',13,COALESCE((SELECT tipo_operacao FROM _modelo_antigo a WHERE a.dia_semana=5 AND a.rota_codigo='513'),''),'','Passos - Maxfrios','planilha da semana 02/09','planilha do dono' WHERE EXISTS (SELECT 1 FROM dim_rotas WHERE codigo = '513') ON CONFLICT (dia_semana, rota_codigo, ordem) DO NOTHING;
INSERT INTO programacao_modelo (dia_semana, rota_codigo, ordem, tipo_operacao, paletizada, apelido_rota, observacoes, criado_por) SELECT 5,'523',14,COALESCE((SELECT tipo_operacao FROM _modelo_antigo a WHERE a.dia_semana=5 AND a.rota_codigo='523'),''),'','Vale do Aço - SS Log','planilha da semana 02/09','planilha do dono' WHERE EXISTS (SELECT 1 FROM dim_rotas WHERE codigo = '523') ON CONFLICT (dia_semana, rota_codigo, ordem) DO NOTHING;
INSERT INTO programacao_modelo (dia_semana, rota_codigo, ordem, tipo_operacao, paletizada, apelido_rota, observacoes, criado_por) SELECT 5,'500',15,COALESCE((SELECT tipo_operacao FROM _modelo_antigo a WHERE a.dia_semana=5 AND a.rota_codigo='500'),''),'','Patos de Minas','planilha da semana 02/09','planilha do dono' WHERE EXISTS (SELECT 1 FROM dim_rotas WHERE codigo = '500') ON CONFLICT (dia_semana, rota_codigo, ordem) DO NOTHING;
INSERT INTO programacao_modelo (dia_semana, rota_codigo, ordem, tipo_operacao, paletizada, apelido_rota, observacoes, criado_por) SELECT 5,'500',16,COALESCE((SELECT tipo_operacao FROM _modelo_antigo a WHERE a.dia_semana=5 AND a.rota_codigo='500'),''),'','Patos de Minas','planilha da semana 02/09','planilha do dono' WHERE EXISTS (SELECT 1 FROM dim_rotas WHERE codigo = '500') ON CONFLICT (dia_semana, rota_codigo, ordem) DO NOTHING;
INSERT INTO programacao_modelo (dia_semana, rota_codigo, ordem, tipo_operacao, paletizada, apelido_rota, observacoes, criado_por) SELECT 5,'504',17,COALESCE((SELECT tipo_operacao FROM _modelo_antigo a WHERE a.dia_semana=5 AND a.rota_codigo='504'),''),'','Arinos / Buritis','planilha da semana 02/09','planilha do dono' WHERE EXISTS (SELECT 1 FROM dim_rotas WHERE codigo = '504') ON CONFLICT (dia_semana, rota_codigo, ordem) DO NOTHING;
INSERT INTO programacao_modelo (dia_semana, rota_codigo, ordem, tipo_operacao, paletizada, apelido_rota, observacoes, criado_por) SELECT 5,'504',18,COALESCE((SELECT tipo_operacao FROM _modelo_antigo a WHERE a.dia_semana=5 AND a.rota_codigo='504'),''),'','Arinos / Buritis','planilha da semana 02/09','planilha do dono' WHERE EXISTS (SELECT 1 FROM dim_rotas WHERE codigo = '504') ON CONFLICT (dia_semana, rota_codigo, ordem) DO NOTHING;
INSERT INTO programacao_modelo (dia_semana, rota_codigo, ordem, tipo_operacao, paletizada, apelido_rota, observacoes, criado_por) SELECT 5,'504',19,COALESCE((SELECT tipo_operacao FROM _modelo_antigo a WHERE a.dia_semana=5 AND a.rota_codigo='504'),''),'','Riachinho','planilha da semana 02/09','planilha do dono' WHERE EXISTS (SELECT 1 FROM dim_rotas WHERE codigo = '504') ON CONFLICT (dia_semana, rota_codigo, ordem) DO NOTHING;
INSERT INTO programacao_modelo (dia_semana, rota_codigo, ordem, tipo_operacao, paletizada, apelido_rota, observacoes, criado_por) SELECT 5,'504',20,COALESCE((SELECT tipo_operacao FROM _modelo_antigo a WHERE a.dia_semana=5 AND a.rota_codigo='504'),''),'','Riachinho','planilha da semana 02/09','planilha do dono' WHERE EXISTS (SELECT 1 FROM dim_rotas WHERE codigo = '504') ON CONFLICT (dia_semana, rota_codigo, ordem) DO NOTHING;
INSERT INTO programacao_modelo (dia_semana, rota_codigo, ordem, tipo_operacao, paletizada, apelido_rota, observacoes, criado_por) SELECT 5,'504',21,COALESCE((SELECT tipo_operacao FROM _modelo_antigo a WHERE a.dia_semana=5 AND a.rota_codigo='504'),''),'','João Pinheiro','planilha da semana 02/09','planilha do dono' WHERE EXISTS (SELECT 1 FROM dim_rotas WHERE codigo = '504') ON CONFLICT (dia_semana, rota_codigo, ordem) DO NOTHING;
INSERT INTO programacao_modelo (dia_semana, rota_codigo, ordem, tipo_operacao, paletizada, apelido_rota, observacoes, criado_por) SELECT 5,'504',22,COALESCE((SELECT tipo_operacao FROM _modelo_antigo a WHERE a.dia_semana=5 AND a.rota_codigo='504'),''),'','Paracatu','planilha da semana 02/09','planilha do dono' WHERE EXISTS (SELECT 1 FROM dim_rotas WHERE codigo = '504') ON CONFLICT (dia_semana, rota_codigo, ordem) DO NOTHING;
INSERT INTO programacao_modelo (dia_semana, rota_codigo, ordem, tipo_operacao, paletizada, apelido_rota, observacoes, criado_por) SELECT 5,'504',23,COALESCE((SELECT tipo_operacao FROM _modelo_antigo a WHERE a.dia_semana=5 AND a.rota_codigo='504'),''),'','Unaí','planilha da semana 02/09','planilha do dono' WHERE EXISTS (SELECT 1 FROM dim_rotas WHERE codigo = '504') ON CONFLICT (dia_semana, rota_codigo, ordem) DO NOTHING;
INSERT INTO programacao_modelo (dia_semana, rota_codigo, ordem, tipo_operacao, paletizada, apelido_rota, observacoes, criado_por) SELECT 5,'502',24,COALESCE((SELECT tipo_operacao FROM _modelo_antigo a WHERE a.dia_semana=5 AND a.rota_codigo='502'),''),'','Araxá','planilha da semana 02/09','planilha do dono' WHERE EXISTS (SELECT 1 FROM dim_rotas WHERE codigo = '502') ON CONFLICT (dia_semana, rota_codigo, ordem) DO NOTHING;
INSERT INTO programacao_modelo (dia_semana, rota_codigo, ordem, tipo_operacao, paletizada, apelido_rota, observacoes, criado_por) SELECT 5,'503',25,COALESCE((SELECT tipo_operacao FROM _modelo_antigo a WHERE a.dia_semana=5 AND a.rota_codigo='503'),''),'','Patrocínio','planilha da semana 02/09','planilha do dono' WHERE EXISTS (SELECT 1 FROM dim_rotas WHERE codigo = '503') ON CONFLICT (dia_semana, rota_codigo, ordem) DO NOTHING;
