#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=24

# Estado do assistente — NÃO é o .env do sistema. Aqui só ficam IP, destino de
# backup e marcas de "esta etapa já passou", para você poder parar no meio e
# voltar amanhã sem repetir nada.
ENV_FILE="${ENV_FILE:-$HOME/.migracao-suinco.conf}"

IP_ANTIGO_PADRAO="2.25.95.253"
DOMINIO_API="api.embarquesuinco.com.br"
BRANCH="claude/pega-visao-up19-deliverables-6cqhjb"
REPO="https://github.com/loxbmuniz-eng/pega-visao.git"
SRC="/opt/suinco-src"
PAINEL="$SRC/entregaveis/suinco_logistica"

# ── Ajudantes deste assistente ────────────────────────────────────────────
# Rodar comando no servidor e mostrar a saída. Falha não mata o assistente:
# quem decide seguir é você, com a saída na frente.
remoto() { ssh -o ConnectTimeout=10 "root@$1" "$2" 2>&1 || true; }

# Mostra o comando ANTES de rodar. Num servidor de produção, você tem o
# direito de ver o que vai ser executado no seu nome.
rodar_remoto() {
  printf '  %s$%s ssh root@%s "%s"\n' "$DIM" "$RESET" "$1" "$2"
  remoto "$1" "$2" | sed 's/^/    /'
}

# As seis contagens que decidem se a virada segue ou volta.
CONTAGENS_SQL="SELECT 'cargas' t, count(*) n FROM fact_viagens
UNION ALL SELECT 'movimentacoes', count(*) FROM fact_statusfrota
UNION ALL SELECT 'devolucoes', count(*) FROM devolucoes
UNION ALL SELECT 'clientes', count(*) FROM dim_clientes
UNION ALL SELECT 'frota', count(*) FROM dim_veiculos
UNION ALL SELECT 'operadores', count(*) FROM operadores ORDER BY t;"

contagens() {
  remoto "$1" "sudo -u postgres psql -qtAF'|' -d embarque_suinco -c \"$CONTAGENS_SQL\""
}

saude() { remoto "$1" "curl -s --max-time 10 http://127.0.0.1:3000/health"; }

marcar() { write_env "$1" "ok"; }
ja_feito() { [[ "$(_existing "$1" 2>/dev/null || true)" == "ok" ]]; }

# RETOMAR DE ONDE PAROU — e isso é o ponto de haver um arquivo de estado.
# A fase 2 leva umas duas horas entre instalador, bateria e backup. Obrigar
# a refazer tudo porque você fechou o terminal transformaria um assistente
# em castigo. Só oferece pular o que é CARO e SEGURO repetir-ou-não: nada
# da fase 3 passa por aqui, porque lá repetir um passo tem consequência.
pular_se_feito() {
  ja_feito "$1" || return 1
  printf '  %s✓ já feito numa execução anterior%s
' "$GREEN" "$RESET"
  confirm "Pular esta etapa?" && return 0
  return 1
}

banner "Mudança de servidor · Embarque Suinco"

# ═══════════════════ FASE 1 — CONTRATAR E PREPARAR ═══════════════════════
# A operação não corre risco nenhum nesta fase. O servidor antigo atende tudo.

stage "Antes de tudo: o que precisa estar na sua máquina"
say "Três coisas. Se alguma faltar, o assistente diz como resolver."
printf '\n'
for prog in ssh scp dig; do
  if command -v "$prog" >/dev/null 2>&1; then
    printf '  %s✓%s %s\n' "$GREEN" "$RESET" "$prog"
  else
    printf '  %s✗%s %s — instale antes de seguir\n' "$RED" "$RESET" "$prog"
  fi
done
printf '\n'
ask IP_ANTIGO "IP do servidor ATUAL [$IP_ANTIGO_PADRAO]:"
[[ -z "$IP_ANTIGO" ]] && IP_ANTIGO="$IP_ANTIGO_PADRAO"
write_env IP_ANTIGO "$IP_ANTIGO"
say "Testando o acesso ao servidor atual…"
if [[ -n "$(saude "$IP_ANTIGO")" ]]; then
  printf '  %s✓%s o servidor atual responde — acesso em ordem\n' "$GREEN" "$RESET"
else
  warn "não consegui falar com o servidor atual. Confira o SSH antes de seguir:"
  note "  ssh root@$IP_ANTIGO"
fi
pause "Enter para seguir"

stage "Contratar o VPS na Hostinger — com a nota no CNPJ da Suinco"
say "É o ponto inteiro desta mudança, e é a primeira coisa porque tudo depende dela."
open_url "https://hpanel.hostinger.com/vps"
step "Criar VPS. Sistema: Ubuntu 24.04 LTS."
step "Tamanho: 2 vCPU, 4 GB de RAM, 50 GB de disco."
note "Folgado de propósito: o banco tem menos de 100 MB hoje, e esse tamanho"
note "cobre dez anos de pátio sem apertar."
step "Região: Brasil, se houver — tira uns 100 ms de cada clique."
warn "NA COBRANÇA, os dados são os da SUINCO (CNPJ), não os seus."
say "É isso que tira o sistema do cartão de uma pessoa. Se passar batido aqui,"
say "a mudança não resolve o que ela existe para resolver."
pause "Quando a máquina estiver criada, Enter"

stage "O IP novo, e a primeira entrada"
say "A Hostinger mostra o IP e a senha de root no painel dela."
ask IP_NOVO "IP do servidor NOVO:"
if [[ -z "$IP_NOVO" ]]; then
  warn "sem o IP não dá para seguir. Rode o assistente de novo quando tiver."
  exit 1
fi
write_env IP_NOVO "$IP_NOVO"
say "Testando…"
if [[ -n "$(remoto "$IP_NOVO" 'hostname')" ]]; then
  printf '  %s✓%s o servidor novo responde: %s\n' "$GREEN" "$RESET" "$(remoto "$IP_NOVO" 'hostname')"
else
  warn "não respondeu. Entre uma vez à mão para aceitar a chave do host:"
  note "  ssh root@$IP_NOVO"
  pause "Depois de conseguir entrar, Enter"
fi

stage "Trocar a senha de root e instalar sua chave"
say "A senha que veio por e-mail não pode ser a senha definitiva de um servidor"
say "de produção. E chave é melhor que senha: não dá para adivinhar por tentativa."
printf '\n'
step "No servidor novo, troque a senha:"
note "  ssh root@$IP_NOVO   →   passwd"
step "E instale sua chave (na SUA máquina):"
if [[ -f "$HOME/.ssh/id_ed25519.pub" ]]; then
  note "  ssh-copy-id root@$IP_NOVO"
else
  note "  ssh-keygen -t ed25519      # você ainda não tem chave"
  note "  ssh-copy-id root@$IP_NOVO"
fi
pause "Quando os dois estiverem feitos, Enter"
marcar FASE1_ACESSO

stage "Clonar o repositório no servidor novo"
say "Mesmo caminho do servidor antigo, para o atualizar.sh funcionar igual depois."
rodar_remoto "$IP_NOVO" "apt-get update -qq && apt-get install -y -qq git && \
  (test -d $SRC || git clone -q $REPO $SRC) && cd $SRC && \
  git fetch -q origin $BRANCH && git checkout -q $BRANCH && git pull -q && git log --oneline -1"
printf '\n'
say "A linha acima é o commit que está no servidor novo. Compare com o antigo:"
rodar_remoto "$IP_ANTIGO" "cd $SRC && git log --oneline -1"
if confirm "Os dois commits são o mesmo?"; then
  marcar FASE1_CLONE
else
  warn "rode de novo ou acerte à mão antes de seguir — a fase 2 testa este código."
  pause "Enter"
fi

# ═══════════════════ FASE 2 — ENSAIAR COM O BANCO REAL ═══════════════════
# Ainda sem risco para a operação. É a fase que transforma a virada em rotina.

stage "Fase 2 começa: o ensaio"
say "Aqui o sistema novo é montado e testado COM OS DADOS REAIS, enquanto o"
say "antigo segue no ar. Se algo não couber no servidor novo, você descobre"
say "agora — de dia, com tempo, sem ninguém esperando."
printf '\n'
note "Nada nesta fase é visível para a operação."
pause "Enter"

stage "Dump de ensaio: do antigo para o novo"
say "Não é o backup final — é a cópia do ensaio. O final sai na fase 3."
rodar_remoto "$IP_ANTIGO" "sudo -u postgres pg_dump -Fc embarque_suinco > /tmp/ensaio.dump && ls -lh /tmp/ensaio.dump"
say "Trazendo para cá e levando para o novo…"
if scp -q "root@$IP_ANTIGO:/tmp/ensaio.dump" /tmp/ensaio.dump 2>&1 && \
   scp -q /tmp/ensaio.dump "root@$IP_NOVO:/tmp/ensaio.dump" 2>&1; then
  printf '  %s✓%s dump no servidor novo\n' "$GREEN" "$RESET"
  rm -f /tmp/ensaio.dump
  marcar FASE2_DUMP
else
  warn "a cópia falhou. Faça à mão:"
  note "  scp root@$IP_ANTIGO:/tmp/ensaio.dump /tmp/"
  note "  scp /tmp/ensaio.dump root@$IP_NOVO:/tmp/"
  pause "Enter quando estiver lá"
fi

stage "Rodar o instalador no servidor novo"
say "Ele monta tudo: Node 22, PostgreSQL 16, Nginx, HTTPS, firewall, o serviço"
say "que sobe no boot, o backup diário, e gera os segredos."
printf '\n'
warn "O HTTPS VAI FALHAR neste ensaio, e está certo."
note "O certificado é emitido validando que $DOMINIO_API aponta para esta"
note "máquina — e ele ainda aponta para a antiga. O instalador avisa e segue."
note "O certificado sai de verdade na fase 3, depois do DNS."
printf '\n'
note "São ~15 min, a maior parte esperando o apt. Não feche a janela."
if pular_se_feito FASE2_INSTALOU; then
  :
elif confirm "Rodar o instalador agora?"; then
  rodar_remoto "$IP_NOVO" "cd $SRC && bash $PAINEL/backend/instalar.sh 2>&1 | tail -40"
  printf '\n'
  say "Conferindo o serviço e o banco…"
  rodar_remoto "$IP_NOVO" "systemctl is-active embarque-suinco"
  S="$(saude "$IP_NOVO")"
  if [[ "$S" == *'"banco":"conectado"'* ]]; then
    printf '  %s✓%s API no ar e banco conectado\n' "$GREEN" "$RESET"
    marcar FASE2_INSTALOU
  else
    warn "a API não respondeu como esperado. Saída: $S"
    note "Veja o log:  ssh root@$IP_NOVO 'journalctl -u embarque-suinco -n 50'"
  fi
else
  SKIPPED+=("rodar o instalador no servidor novo")
fi
pause "Enter"

stage "Restaurar o banco do ensaio"
rodar_remoto "$IP_NOVO" "sudo -u postgres pg_restore -d embarque_suinco --clean --if-exists /tmp/ensaio.dump 2>&1 | tail -5; \
  sudo -u postgres psql -qtAc \"SELECT count(*) FROM fact_viagens\" -d embarque_suinco"
printf '\n'
say "E no antigo, para comparar:"
rodar_remoto "$IP_ANTIGO" "sudo -u postgres psql -qtAc \"SELECT count(*) FROM fact_viagens\" -d embarque_suinco"
if confirm "As duas contagens de carga batem?"; then
  marcar FASE2_RESTAUROU
else
  warn "não siga. Me mande as duas saídas antes de continuar."
  pause "Enter"
fi

stage "A bateria completa contra o servidor novo"
say "É o passo que mais vale nesta fase, e o único que não dá para pular."
say "152 suítes de tela e 53 blocos de API contra a máquina nova, com os dados"
say "reais. Versão, locale, fuso ou permissão diferente aparece AQUI."
printf '\n'
note "~35 min, a maior parte esperando."
if pular_se_feito FASE2_BATERIA; then
  :
elif confirm "Rodar a bateria agora?"; then
  rodar_remoto "$IP_NOVO" "cd $PAINEL/backend && npm run teste 2>&1 | tail -8"
  printf '\n'
  rodar_remoto "$IP_NOVO" "cd $PAINEL && bash testes/rodar_tudo.sh 2>&1 | tail -12"
  printf '\n'
  warn "PARE se não deu verde nos dois."
  say "Vermelho aqui é informação obtida de graça, com o sistema antigo intacto"
  say "no ar. Me mande a saída e eu digo qual das quatro causas é."
  if confirm "Deu 415 de 415 na API e 152 verdes na tela?"; then
    marcar FASE2_BATERIA
  else
    warn "não siga para a fase 3. É exatamente o que este ensaio existe para impedir."
    pause "Enter"
  fi
else
  SKIPPED+=("BATERIA COMPLETA no servidor novo — não vire o DNS sem ela")
  warn "anotado como pendência. Não vire o DNS sem isso."
  pause "Enter"
fi

stage "Copiar o .env — para ninguém ser deslogado às 2h da manhã"
say "O instalador gerou segredos novos. Se eles ficarem, todo mundo é deslogado"
say "no instante em que o DNS virar — sem entender por quê."
say "Copiando o .env antigo, o segredo de sessão continua o mesmo e NINGUÉM"
say "percebe a troca."
printf '\n'
warn "A cópia intermediária tem a senha do banco em texto. Ela é apagada no fim."
if confirm "Copiar o .env do antigo para o novo?"; then
  T="$(mktemp)"
  if scp -q "root@$IP_ANTIGO:/opt/embarque-suinco/.env" "$T" && \
     scp -q "$T" "root@$IP_NOVO:/opt/embarque-suinco/.env"; then
    rm -f "$T"
    printf '  %s✓%s .env copiado, e a cópia local apagada\n' "$GREEN" "$RESET"
    say "Reconciliando a senha do banco (o instalador faz isso)…"
    rodar_remoto "$IP_NOVO" "cd $SRC && bash $PAINEL/backend/instalar.sh 2>&1 | tail -12"
    S="$(saude "$IP_NOVO")"
    if [[ "$S" == *'"banco":"conectado"'* ]]; then
      printf '  %s✓%s banco continua conectado depois da troca de senha\n' "$GREEN" "$RESET"
      marcar FASE2_ENV
    else
      warn "a API parou de conectar. Saída: $S"
    fi
  else
    rm -f "$T"
    warn "a cópia falhou. Se você seguir sem isso, todos terão de logar de novo."
  fi
else
  SKIPPED+=("copiar o .env (todos terão de logar de novo na virada)")
fi
pause "Enter"

stage "O backup que sai do servidor"
say "Faça agora, no servidor novo, e o buraco mais grave que existe hoje nasce"
say "fechado: o backup atual mora DENTRO da máquina que ele protege."
printf '\n'
step "O rclone vai abrir um questionário. Escolha o destino da Suinco:"
note "  Google Drive (n/drive) · OneDrive · Backblaze B2 · Amazon S3"
note "O mais simples é o Drive da conta da empresa; o mais barato para dez"
note "anos é o Backblaze."
printf '\n'
say "Rode ISTO numa outra janela do terminal (é interativo):"
printf '  %s$%s ssh root@%s\n' "$DIM" "$RESET" "$IP_NOVO"
printf '  %s$%s apt-get install -y rclone && rclone config\n' "$DIM" "$RESET"
printf '\n'
ask DESTINO_BACKUP "Nome do destino que você criou no rclone (ex: suinco-drive):"
if pular_se_feito FASE2_BACKUP; then
  :
elif [[ -n "$DESTINO_BACKUP" ]]; then
  write_env DESTINO_BACKUP "$DESTINO_BACKUP"
  say "Rodando o backup para fora…"
  rodar_remoto "$IP_NOVO" "BACKUP_REMOTO='$DESTINO_BACKUP:embarque-suinco' bash $PAINEL/backend/scripts/backup_para_fora.sh 2>&1 | tail -12"
  printf '\n'
  note "O script confere o tamanho do arquivo NO DESTINO — não confia em"
  note "\"o rclone não deu erro\". Abra a pasta na nuvem e veja o arquivo lá."
  if confirm "O arquivo está na nuvem?"; then marcar FASE2_BACKUP; fi
else
  SKIPPED+=("destino do backup fora do servidor — é o risco mais grave em aberto")
fi
pause "Enter"

stage "Testar a restauração do backup"
say "Backup que ninguém restaurou não é backup: é um arquivo com nome de backup."
say "O script restaura num banco descartável e compara tabela por tabela."
rodar_remoto "$IP_NOVO" "bash $PAINEL/backend/scripts/testar_restauracao_backup.sh 2>&1 | tail -15"
if confirm "A restauração passou?"; then marcar FASE2_TESTE_RESTORE; fi
pause "Enter"

# ═══════════════════════ FASE 3 — A VIRADA ═══════════════════════════════

stage "Fase 3: daqui para frente a operação sente"
warn "Só siga se a fase 2 deu verde."
printf '\n'
say "O que vem agora é de madrugada. A operação CONTINUA registrando — o painel"
say "trabalha offline e a fila fica no aparelho. O que pausa é os setores se"
say "VEREM, e é por isso que a hora importa."
printf '\n'
note "Até a etapa 18 a volta atrás é uma linha de DNS."
if ! confirm "A fase 2 deu verde e você está na janela combinada?"; then
  say "Certo. Pare aqui e rode o assistente de novo na hora."
  finish
  exit 0
fi

stage "Avisar os oito setores — na véspera"
say "Uma frase em cada grupo, com hora:"
printf '\n'
note "  \"Entre 1h e 2h o painel vai trabalhar offline. Continue registrando"
note "   normalmente — nada se perde. Os setores voltam a se ver às 2h.\""
printf '\n'
say "Sem esse aviso, a primeira pessoa que não vê a carga do colega conclui que"
say "o sistema quebrou. E liga para você, à 1h40."
if confirm "Os oito setores foram avisados?"; then marcar FASE3_AVISO; fi

stage "Baixar o TTL do DNS — 24 horas ANTES"
warn "É o passo que mais se esquece, e o que mais custa esquecer."
say "O TTL diz por quanto tempo os provedores guardam o endereço antigo em"
say "cache. Em 24h, sua janela de 50 minutos vira um dia com metade dos"
say "terminais em cada servidor. Nada se perde — cada um enfileira o seu — mas"
say "a coordenação fica partida por horas."
printf '\n'
open_url "https://registro.br/"
step "Entre, abra embarquesuinco.com.br → Editar zona DNS."
step "No registro A de 'api', baixe o TTL para 300 segundos."
step "Salve e espere o TTL ANTIGO expirar — por isso é 24h antes."
printf '\n'
say "TTL atual, agora:"
dig +noall +answer "$DOMINIO_API" | sed 's/^/    /' || true
if confirm "O TTL já está em 300 e passaram 24h?"; then marcar FASE3_TTL; fi

stage "Congelar o antigo e tirar o dump final"
warn "A JANELA COMEÇA AGORA."
say "Parar a API é o que garante que nada é gravado no banco antigo depois"
say "desta foto. Os terminais passam a enfileirar — comportamento normal e"
say "testado: o painel avisa na tela e guarda as gravações."
printf '\n'
if ! confirm "Parar a API do servidor antigo agora?"; then
  say "Certo, nada foi feito. Rode de novo quando estiver na hora."
  finish; exit 0
fi
rodar_remoto "$IP_ANTIGO" "systemctl stop embarque-suinco && systemctl is-active embarque-suinco"
rodar_remoto "$IP_ANTIGO" "sudo -u postgres pg_dump -Fc embarque_suinco > /tmp/final.dump && ls -lh /tmp/final.dump"
marcar FASE3_CONGELOU

stage "Restaurar no novo e conferir as SEIS contagens"
say "Esta é a conferência que decide se a virada segue ou volta."
T="$(mktemp)"
scp -q "root@$IP_ANTIGO:/tmp/final.dump" "$T" && scp -q "$T" "root@$IP_NOVO:/tmp/final.dump" && rm -f "$T"
rodar_remoto "$IP_NOVO" "systemctl stop embarque-suinco; \
  sudo -u postgres pg_restore -d embarque_suinco --clean --if-exists /tmp/final.dump 2>&1 | tail -4; \
  systemctl start embarque-suinco; sleep 3; systemctl is-active embarque-suinco"
printf '\n'
say "Comparando as seis contagens…"
A="$(contagens "$IP_ANTIGO")"
N="$(contagens "$IP_NOVO")"
printf '\n  %-18s %12s %12s\n' "tabela" "antigo" "novo"
DIFERENCA=0
while IFS='|' read -r t n; do
  [[ -z "$t" ]] && continue
  nn="$(printf '%s\n' "$N" | awk -F'|' -v k="$t" '$1==k{print $2}')"
  if [[ "$n" == "$nn" ]]; then
    printf '  %s✓%s %-16s %12s %12s\n' "$GREEN" "$RESET" "$t" "$n" "$nn"
  else
    printf '  %s✗%s %-16s %12s %12s  <<< DIFERENTE\n' "$RED" "$RESET" "$t" "$n" "$nn"
    DIFERENCA=1
  fi
done <<< "$A"
printf '\n'
if [[ "$DIFERENCA" -ne 0 ]]; then
  warn "CONTAGEM DIFERENTE. Não siga."
  say "A volta é imediata, e ninguém na operação fica sabendo:"
  note "  ssh root@$IP_ANTIGO 'systemctl start embarque-suinco'"
  if confirm "Quer que eu religue o servidor antigo agora?"; then
    rodar_remoto "$IP_ANTIGO" "systemctl start embarque-suinco && systemctl is-active embarque-suinco"
    say "Servidor antigo de volta. O DNS nunca virou — está tudo como era."
  fi
  finish; exit 1
fi
printf '  %s✓%s as seis contagens batem\n' "$GREEN" "$RESET"
marcar FASE3_CONTAGENS
pause "Enter para virar o DNS"

stage "Virar o DNS e emitir o certificado"
open_url "https://registro.br/"
step "Editar zona DNS → registro A de 'api'."
step "Troque $IP_ANTIGO por $IP_NOVO. Salve."
printf '\n'
say "Esperando a propagação (com TTL em 300s, são minutos)…"
for i in $(seq 1 40); do
  ATUAL="$(dig +short "$DOMINIO_API" | tail -1)"
  if [[ "$ATUAL" == "$IP_NOVO" ]]; then
    printf '\n  %s✓%s %s já responde %s\n' "$GREEN" "$RESET" "$DOMINIO_API" "$IP_NOVO"
    break
  fi
  printf '  %s· tentativa %s/40 — ainda responde %s%s\n' "$DIM" "$i" "${ATUAL:-nada}" "$RESET"
  sleep 15
done
printf '\n'
if confirm "O DNS já aponta para o servidor novo? Emitir o certificado?"; then
  rodar_remoto "$IP_NOVO" "certbot --nginx -d $DOMINIO_API --non-interactive --agree-tos -m lo.xbmuniz@gmail.com 2>&1 | tail -8"
  say "Conferindo o HTTPS de fora:"
  curl -s --max-time 15 "https://$DOMINIO_API/health" | sed 's/^/    /' || warn "não respondeu ainda"
  marcar FASE3_DNS
fi
pause "Enter"

stage "Drenar as filas e confirmar em DOIS aparelhos"
say "Os terminais reconectam sozinhos e sobem o que registraram na janela."
printf '\n'
warn "Não basta um aparelho funcionar."
say "A prova é DOIS aparelhos diferentes vendo a mesma carga — é isso que"
say "significa \"os setores voltaram a se ver\"."
printf '\n'
open_url "https://embarquesuinco.com.br"
step "Abra o painel em dois celulares."
step "Crie uma carga de teste num deles."
step "Veja ela aparecer no outro. Depois exclua."
printf '\n'
warn "ESTE É O ÚLTIMO PONTO DE VOLTA ATRÁS."
note "Depois daqui há cargas novas no servidor novo que não existem no antigo."
note "Voltar passa a exigir trazer esses dados — possível, mas já não é uma"
note "linha de DNS."
if confirm "A carga de teste apareceu nos dois aparelhos?"; then
  marcar FASE3_CONFIRMADO
  printf '\n  %s✓ A VIRADA ESTÁ FEITA.%s\n' "$GREEN$BOLD" "$RESET"
else
  warn "me chame antes de seguir."
fi
pause "Enter"

# ═══════════════════════ FASE 4 — FECHAR ═════════════════════════════════

stage "Diagnóstico completo do servidor novo"
say "Confere serviço, banco, certificado, firewall, backup e disco de uma vez."
rodar_remoto "$IP_NOVO" "bash $PAINEL/backend/diagnostico.sh 2>&1 | tail -30"
if confirm "O diagnóstico está limpo?"; then marcar FASE4_DIAGNOSTICO; fi
pause "Enter"

stage "O backup diário rodou sozinho?"
say "No dia seguinte, antes de desligar o antigo. É a diferença entre"
say "\"configurei o backup\" e \"o backup está funcionando\"."
rodar_remoto "$IP_NOVO" "ls -lh /var/backups/embarque-suinco/ | tail -5"
if [[ -n "${DESTINO_BACKUP:-}" ]]; then
  rodar_remoto "$IP_NOVO" "rclone lsl '$DESTINO_BACKUP:embarque-suinco/' 2>&1 | tail -4"
fi
if confirm "O backup do dia está nos dois lugares?"; then marcar FASE4_BACKUP_DIARIO; fi
pause "Enter"

stage "Subir o TTL do DNS de volta"
say "Os 300 segundos serviram à virada. Deixar assim para sempre faz cada"
say "aparelho perguntar o endereço a cada 5 minutos, sem motivo."
open_url "https://registro.br/"
step "Editar zona DNS → registro A de 'api' → TTL de volta para 3600."
if confirm "TTL restaurado?"; then marcar FASE4_TTL; fi

stage "Sete dias depois: desligar o antigo"
say "O servidor velho fica ligado, sem receber nada, por uma semana. É o botão"
say "de arrependimento — e uma semana cobre o ciclo inteiro da operação,"
say "incluindo o pico de sexta e o fechamento de programação."
printf '\n'
warn "ANTES DE CANCELAR, tire um dump final e guarde fora."
say "Não para usar: para ter. É o registro de como estava no dia da troca."
printf '\n'
if confirm "Já passaram sete dias com o diagnóstico limpo?"; then
  rodar_remoto "$IP_ANTIGO" "sudo -u postgres pg_dump -Fc embarque_suinco > /tmp/antes-da-troca.dump && ls -lh /tmp/antes-da-troca.dump"
  say "Baixe esse arquivo e guarde junto dos backups:"
  note "  scp root@$IP_ANTIGO:/tmp/antes-da-troca.dump ."
  pause "Enter quando tiver guardado"
  open_url "https://hpanel.hostinger.com/vps"
  step "Cancele o VPS antigo."
  say "A última conta chega para quem hoje a paga — que é o outro motivo desta"
  say "mudança toda."
  marcar FASE4_DESLIGOU
else
  note "Certo. Rode o assistente de novo em sete dias — ele lembra onde parou."
fi

finish
