"""Roteiro de cada guia: o que cada setor faz, na ordem em que faz.

Cada passo é escrito na linguagem de quem opera, e responde sempre às
mesmas quatro perguntas — O QUE, ONDE, POR QUE e QUANDO — porque é isso
que falta num manual de tela: a pessoa entende o botão e não entende o
momento de usá-lo.

Campos de um passo:
  titulo    — a ação, no infinitivo
  oque/onde/porque/quando — os quatro blocos didáticos
  tab       — aba a abrir antes do print
  destaque  — seletor CSS que recebe o realce no print
  antes     — lista de ações [(tipo, seletor, valor)] executadas antes
  atencao   — aviso opcional (caixa âmbar)
  cenario   — chave do cenário de dados que este passo exige
"""

SENHA_DEMO = 'guia-demo-123'

GUIAS = {
  'Portaria': {
    'email': 'guia.portaria@suinco.demo',
    'icone': '🚧',
    'missao': 'Registrar quem entra e quem sai do pátio, e receber as devoluções que voltam.',
    'resumo': [
      'Você é o primeiro e o último carimbo de toda carga: registra a CHEGADA do caminhão e registra a SAÍDA dele.',
      'Na saída, informe o número do lacre junto com a placa.',
      'Quando um caminhão volta com devolução, você confirma o recebimento e diz se ele chegou lacrado ou não.',
    ],
    'passos': [
      {
        'titulo': 'Entrar no painel',
        'tab': None, 'destaque': '#login-servidor',
        'oque': 'Entrar com o seu e-mail e a sua senha.',
        'onde': 'Tela de entrada, que aparece antes do painel.',
        'porque': 'Tudo o que você registra fica assinado com o seu nome — é assim que a empresa sabe quem fez cada movimento, e é assim que ninguém responde pelo que não fez.',
        'quando': 'Uma vez por turno. O painel lembra de você no mesmo aparelho.',
      },
      {
        'titulo': 'Registrar que o caminhão CHEGOU',
        'tab': 'portaria', 'destaque': '#portaria-placa',
        'antes': [('fill', '#portaria-placa', 'RRP5F95')],
        'oque': 'Digitar a placa e apertar o botão verde "Chegou".',
        'onde': 'Aba Portaria → cartão "Registrar Movimento de Placa".',
        'porque': 'É o que avisa a Expedição de que o veículo está no pátio. Enquanto você não registra, para o resto da empresa aquele caminhão não chegou.',
        'quando': 'Assim que o caminhão entra na portaria, antes de qualquer outra coisa.',
        'atencao': 'Se a placa não tiver programação, o "Chegou" cria sozinho uma entrada "Aguardando Carga" — você não precisa fazer mais nada.',
      },
      {
        'titulo': 'Registrar a SAÍDA com o número do lacre',
        'tab': 'portaria', 'destaque': '#portaria-lacre',
        'antes': [('fill', '#portaria-placa', 'PWA4C30'), ('fill', '#portaria-lacre', '133476')],
        'oque': 'Digitar a placa, digitar o número do lacre no campo ao lado e apertar "Saiu".',
        'onde': 'Aba Portaria → mesmo cartão, campo "Nº do lacre (na saída)".',
        'porque': 'O lacre é o que prova que a carga saiu fechada. O número fica guardado na carga e aparece na ficha e nos relatórios.',
        'quando': 'No momento em que o caminhão deixa o pátio — todas as cargas daquela placa saem juntas, porque é o mesmo caminhão.',
        'atencao': 'O lacre NÃO trava a saída: se você não informar, a carga segue viagem do mesmo jeito e o painel avisa que saiu sem número. Informe sempre que houver.',
      },
      {
        'titulo': 'Registrar um lacre RETIDO na inspeção',
        'tab': 'portaria', 'destaque': '#card-lacre-retido',
        'oque': 'Informar o número do lacre retido, o novo lacre (se houver) e o motivo.',
        'onde': 'Aba Portaria → cartão "Lacre Retido".',
        'porque': 'Quando a inspeção abre o caminhão, o lacre é cortado. O número retido e o novo ficam registrados na carga, com o motivo e o seu nome.',
        'quando': 'Sempre que um lacre for rompido ou retido na conferência da saída.',
      },
      {
        'titulo': 'Ver as devoluções que estão na SUA fila',
        'tab': 'devolucoes', 'destaque': '#dev-pipeline',
        'oque': 'Olhar a esteira no topo da aba Devoluções: a etapa destacada é a sua.',
        'onde': 'Aba Devoluções → cartão da esteira, no topo.',
        'porque': 'A esteira mostra em que ponto está cada checklist do dia. Quando um chega na sua etapa, ele aparece marcado com "SUA VEZ" no topo da lista.',
        'quando': 'Sempre que chegar um caminhão de devolução — e ao longo do dia, para não deixar nada parado na sua etapa.',
      },
      {
        'titulo': 'Receber a devolução: lacre, placa e motorista',
        'tab': 'devolucoes', 'destaque': '.dev-etapa-acao',
        'cenario': 'devolucao_lancada',
        'oque': 'Responder se o caminhão chegou LACRADO (e o número), conferir a placa, o motorista e a transportadora, e apertar o botão da etapa.',
        'onde': 'Aba Devoluções → checklist marcado com SUA VEZ → linha de ação embaixo do cabeçalho.',
        'porque': 'É o seu carimbo: a partir dele o Faturamento sabe que a devolução chegou. A placa puxa sozinha a transportadora e o motorista do cadastro de Frota.',
        'quando': 'Quando o caminhão da devolução encosta na portaria.',
        'atencao': 'Se o caminhão veio SEM lacre, escolha "Não — chegou SEM lacre". Deixar em branco não é a mesma coisa: em branco quer dizer "ninguém informou".',
      },
      {
        'titulo': 'Imprimir o comprovante do motorista',
        'tab': 'devolucoes', 'destaque': 'button[onclick^="comprovantePortariaUI"]',
        'cenario': 'devolucao_recebida',
        'oque': 'Gerar o comprovante em PDF e entregar ao motorista.',
        'onde': 'Aba Devoluções → checklist já recebido → botão "Comprovante do motorista".',
        'porque': 'Substitui o papel escrito à mão: o motorista leva o comprovante com a carga, a placa e o lacre, e o Faturamento sabe exatamente qual devolução é a dele.',
        'quando': 'Logo depois de registrar o recebimento, com o motorista ainda na portaria.',
      },
    ],
  },

  'Faturamento': {
    'email': 'guia.faturamento@suinco.demo',
    'icone': '🧾',
    'missao': 'Faturar as cargas prontas e conferir na balança o peso do que voltou.',
    'resumo': [
      'Na aba Faturamento você fatura as cargas que a Expedição terminou de embarcar.',
      'Nas devoluções, você é a segunda etapa: pesa e dá o OK para a Expedição descarregar.',
      'O peso final e a pesagem por item são campos SEUS — mais ninguém escreve neles.',
    ],
    'passos': [
      {
        'titulo': 'Entrar no painel',
        'tab': None, 'destaque': '#login-servidor',
        'oque': 'Entrar com o seu e-mail e a sua senha.',
        'onde': 'Tela de entrada.',
        'porque': 'Cada faturamento fica assinado com o seu nome e a hora.',
        'quando': 'Uma vez por turno.',
      },
      {
        'titulo': 'Faturar uma carga',
        'tab': 'faturamento', 'destaque': '#tab-faturamento .card',
        'oque': 'Encontrar a carga com embarque finalizado e apertar o botão de faturar.',
        'onde': 'Aba Faturamento → fila do dia.',
        'porque': 'É o passo que libera o caminhão para a Portaria dar a saída. Enquanto não estiver faturada, a carga não sai do pátio.',
        'quando': 'Assim que a Expedição finaliza o embarque.',
      },
      {
        'titulo': 'Ver as devoluções que estão na SUA fila',
        'tab': 'devolucoes', 'destaque': '#dev-pipeline',
        'oque': 'Olhar a esteira: quando a Portaria recebe uma devolução, ela cai na sua etapa.',
        'onde': 'Aba Devoluções → esteira no topo.',
        'porque': 'É a fila que substitui o "me avisa quando chegar": o checklist aparece sozinho marcado com SUA VEZ.',
        'quando': 'Ao longo do dia, e sempre que o motorista aparecer com o comprovante da portaria.',
      },
      {
        'titulo': 'Pesar item por item',
        'tab': 'devolucoes', 'destaque': '.dev-cel-pesagem, td.c-peso',
        'cenario': 'devolucao_recebida',
        'oque': 'Lançar o peso de cada linha na coluna PESAGEM.',
        'onde': 'Aba Devoluções → checklist aberto → coluna "Pesagem" na tabela de itens.',
        'porque': 'É a confirmação de que aquela linha passou pela balança. A coluna é sua: os outros setores veem, mas não escrevem.',
        'quando': 'Com a carga na balança, antes de dar o OK.',
      },
      {
        'titulo': 'Informar o peso final e dar o OK',
        'tab': 'devolucoes', 'destaque': '.dev-etapa-acao',
        'cenario': 'devolucao_recebida',
        'oque': 'Preencher o peso final e apertar o botão da etapa.',
        'onde': 'Aba Devoluções → linha de ação do checklist.',
        'porque': 'O seu OK passa a devolução para a Expedição descarregar. O peso final também pode ser corrigido depois, no cabeçalho.',
        'quando': 'Terminada a pesagem.',
        'atencao': 'O peso é opcional para não travar a fila num dia corrido — mas é ele que fecha a conferência depois.',
      },
      {
        'titulo': 'Gerar os relatórios do dia',
        'tab': 'relatorios', 'destaque': '#tab-relatorios .card',
        'oque': 'Escolher o dia e gerar o PDF.',
        'onde': 'Aba Relatórios.',
        'porque': 'O PDF sai igual em qualquer aparelho, com o status ATUAL de cada carga e de cada devolução — não com o que estava na tela.',
        'quando': 'No fechamento do turno, ou quando alguém pedir o consolidado.',
      },
    ],
  },

  'Expedição': {
    'email': 'guia.expedicao@suinco.demo',
    'icone': '🚛',
    'missao': 'Embarcar as cargas e conferir, caixa por caixa, o que volta nas devoluções.',
    'resumo': [
      'Você move a carga pelas duas etapas mais longas do fluxo: embarque iniciado e embarque finalizado.',
      'Nas devoluções, você confere a quantidade que realmente chegou — e o sistema aponta a falta sozinho.',
      'A coluna de conferência é sua; pesagem e destinação são de outros setores.',
    ],
    'passos': [
      {
        'titulo': 'Entrar no painel',
        'tab': None, 'destaque': '#login-servidor',
        'oque': 'Entrar com o seu e-mail e a sua senha.',
        'onde': 'Tela de entrada.',
        'porque': 'Cada etapa de embarque fica assinada com o seu nome e a hora.',
        'quando': 'Uma vez por turno.',
      },
      {
        'titulo': 'Iniciar e finalizar o embarque',
        'tab': 'expedicao', 'destaque': '#tab-expedicao .card',
        'oque': 'Achar a carga na fila e apertar o botão da etapa.',
        'onde': 'Aba Expedição.',
        'porque': 'São esses dois carimbos que formam o tempo de pátio — é por eles que a empresa enxerga onde o dia atrasou.',
        'quando': 'Ao encostar o caminhão na doca e ao terminar de carregar.',
      },
      {
        'titulo': 'Conferir a descarga da devolução',
        'tab': 'devolucoes', 'destaque': 'input[title^="Conferência da Expedição"]',
        'cenario': 'devolucao_faturada',
        'oque': 'Lançar, em cada linha, a quantidade de caixas que realmente chegou.',
        'onde': 'Aba Devoluções → checklist aberto → coluna "Expedição".',
        'porque': 'O checklist diz 5, chegou 3: o sistema aponta a falta de 2 sozinho, e ninguém precisa fazer conta nem discutir depois.',
        'quando': 'Durante a descarga, com a mercadoria na mão.',
        'atencao': 'Produto que chegou FORA da lista não é conferência sua: quem lança divergente são os Controles Internos.',
      },
      {
        'titulo': 'Dar o OK da descarga',
        'tab': 'devolucoes', 'destaque': '.dev-etapa-acao',
        'cenario': 'devolucao_faturada',
        'oque': 'Apertar o botão da etapa depois de conferir todas as linhas.',
        'onde': 'Aba Devoluções → linha de ação do checklist.',
        'porque': 'Passa a devolução para os Controles Internos destinarem a mercadoria. No caso de SOBRA, o seu OK encerra o processo.',
        'quando': 'Terminada a conferência.',
      },
      {
        'titulo': 'Acompanhar os indicadores',
        'tab': 'indicadores', 'destaque': '#tab-indicadores',
        'oque': 'Olhar os números do período — tempo de pátio, volume, ocupação.',
        'onde': 'Aba Indicadores.',
        'porque': 'A Expedição é o único posto operacional com indicadores, porque é o único que consegue mudar o número no mesmo turno: remanejar doca, cobrar conferente, reordenar fila.',
        'quando': 'No meio e no fim do turno.',
      },
    ],
  },

  'Controles Internos': {
    'email': 'guia.controles@suinco.demo',
    'icone': '🧭',
    'missao': 'Dizer para onde vai cada caixa que voltou e registrar o que chegou fora da lista.',
    'resumo': [
      'Você recebe a devolução já conferida e decide o destino de cada caixa: estoque, descarte ou reprocesso.',
      'Uma linha pode ter mais de um destino — 3 caixas podem virar 1 estoque e 2 descarte.',
      'Produto divergente e RDC (romaneio) são áreas exclusivamente suas.',
    ],
    'passos': [
      {
        'titulo': 'Entrar no painel',
        'tab': None, 'destaque': '#login-servidor',
        'oque': 'Entrar com o seu e-mail e a sua senha.',
        'onde': 'Tela de entrada.',
        'porque': 'A destinação fica assinada — é ela que responde "quem mandou isso para descarte".',
        'quando': 'Uma vez por turno.',
      },
      {
        'titulo': 'Ver o que está na SUA fila',
        'tab': 'devolucoes', 'destaque': '#dev-pipeline',
        'oque': 'Olhar a esteira: o que a Expedição conferiu cai na sua etapa.',
        'onde': 'Aba Devoluções → esteira no topo.',
        'porque': 'Você não precisa procurar: o checklist aparece marcado com SUA VEZ.',
        'quando': 'Ao longo do dia.',
      },
      {
        'titulo': 'Destinar as caixas (pode ser mais de um destino)',
        'tab': 'devolucoes', 'destaque': '.dev-dest-grupo',
        'cenario': 'devolucao_conferida',
        'oque': 'Preencher quantas caixas vão para Estoque (E), Descarte (D) e Reprocesso (R).',
        'onde': 'Aba Devoluções → checklist aberto → coluna "Destinação".',
        'porque': 'Na prática, a mesma linha se divide: 1 caixa volta para o estoque e 2 vão para descarte. Os três campos existem exatamente para isso.',
        'quando': 'Depois da conferência da Expedição, com a mercadoria separada.',
      },
      {
        'titulo': 'Lançar produto DIVERGENTE',
        'tab': 'devolucoes', 'destaque': '.dev-diverg-form',
        'cenario': 'devolucao_conferida',
        'oque': 'Informar o código do produto que chegou fora da lista, as caixas e uma observação.',
        'onde': 'Aba Devoluções → bloco "Produtos divergentes", embaixo da tabela.',
        'porque': 'Divergente é o que veio sem estar no checklist. Ele NÃO abate a falta do item que faltou — são coisas diferentes, e o sistema mantém as duas visíveis.',
        'quando': 'Sempre que aparecer mercadoria fora do checklist.',
        'atencao': 'Essa área é exclusiva dos Controles Internos: nenhum outro setor lança divergente.',
      },
      {
        'titulo': 'Informar o RDC (romaneio) e destinar',
        'tab': 'devolucoes', 'destaque': '.dev-etapa-acao',
        'cenario': 'devolucao_conferida',
        'oque': 'Responder se gerou RDC, escrever a observação se precisar, e apertar o botão da etapa.',
        'onde': 'Aba Devoluções → linha de ação do checklist.',
        'porque': 'O RDC é a ligação com o romaneio; a resposta fica registrada e sai no relatório. Depois do seu OK, a devolução segue para a Central de Notas.',
        'quando': 'Terminada a destinação de todas as linhas.',
      },
    ],
  },

  'Central de Notas': {
    'email': 'guia.notas@suinco.demo',
    'icone': '📑',
    'missao': 'Fechar a nota de cada devolução destinada.',
    'resumo': [
      'Você é a última etapa: quando a nota está finalizada, o ciclo daquela devolução acaba.',
      'O tique de "Nota final" em cada item é campo seu — mais ninguém marca.',
      'Sobras não passam por você: elas encerram no OK da Expedição.',
    ],
    'passos': [
      {
        'titulo': 'Entrar no painel',
        'tab': None, 'destaque': '#login-servidor',
        'oque': 'Entrar com o seu e-mail e a sua senha.',
        'onde': 'Tela de entrada.',
        'porque': 'O fechamento da nota fica assinado com o seu nome e a hora.',
        'quando': 'Uma vez por turno.',
      },
      {
        'titulo': 'Ver o que está na SUA fila',
        'tab': 'devolucoes', 'destaque': '#dev-pipeline',
        'oque': 'Olhar a esteira: o que os Controles Internos destinaram cai na sua etapa.',
        'onde': 'Aba Devoluções → esteira no topo.',
        'porque': 'O checklist chega até você marcado com SUA VEZ, com a destinação já resolvida.',
        'quando': 'Ao longo do dia.',
      },
      {
        'titulo': 'Marcar a nota final de cada item',
        'tab': 'devolucoes', 'destaque': '.dev-cel-notafinal',
        'cenario': 'devolucao_destinada',
        'oque': 'Marcar o tique na coluna "Nota final" das linhas com a nota já emitida.',
        'onde': 'Aba Devoluções → checklist aberto → última coluna da tabela.',
        'porque': 'É o controle linha a linha: dá para ver o que já foi resolvido e o que ainda falta dentro do mesmo checklist.',
        'quando': 'À medida que as notas vão sendo emitidas.',
      },
      {
        'titulo': 'Finalizar a devolução',
        'tab': 'devolucoes', 'destaque': '.dev-etapa-acao',
        'cenario': 'devolucao_destinada',
        'oque': 'Apertar o botão da última etapa.',
        'onde': 'Aba Devoluções → linha de ação do checklist.',
        'porque': 'Encerra o ciclo: os seis carimbos ficam completos e o checklist vira histórico auditável.',
        'quando': 'Quando todas as notas daquele checklist estiverem resolvidas.',
      },
    ],
  },

  'Logística': {
    'email': 'guia.logistica@suinco.demo',
    'icone': '📋',
    'missao': 'Programar as cargas do dia e lançar os checklists de devolução.',
    'resumo': [
      'Você abre o dia: programa as cargas e acompanha o pátio inteiro pela Torre de Controle.',
      'Nas devoluções, você lança o checklist e tem controle total dele — os outros setores só assinam a própria etapa.',
      'Os relatórios do dia saem daqui, inclusive a relação que vai para o operador do monitoramento.',
    ],
    'passos': [
      {
        'titulo': 'Entrar no painel',
        'tab': None, 'destaque': '#login-servidor',
        'oque': 'Entrar com o seu e-mail e a sua senha.',
        'onde': 'Tela de entrada.',
        'porque': 'Tudo o que você cria e edita fica assinado.',
        'quando': 'Uma vez por turno.',
      },
      {
        'titulo': 'Acompanhar o pátio pela Torre de Controle',
        'tab': 'torre', 'destaque': '#torre-stats, .stat-grid',
        'oque': 'Olhar as caixas do topo: elas contam o dia e filtram a lista quando você clica.',
        'onde': 'Aba Torre de Controle.',
        'porque': 'É a visão de comando: quantos caminhões estão no pátio, quantos já saíram, o que está parado.',
        'quando': 'O tempo todo — é a tela que fica aberta.',
      },
      {
        'titulo': 'Programar uma carga',
        'tab': 'programacao', 'destaque': '#tab-programacao .card',
        'oque': 'Preencher placa, cliente, destino, rota e peso, e criar a carga.',
        'onde': 'Aba Programação.',
        'porque': 'É a carga programada que faz a Portaria reconhecer o caminhão quando ele chega.',
        'quando': 'Na abertura do dia, e sempre que entrar carga nova.',
        'atencao': 'A placa precisa estar no cadastro de Frota — é ela que traz a transportadora e o motorista.',
      },
      {
        'titulo': 'Lançar o checklist de devolução',
        'tab': 'devolucoes', 'destaque': '#dev-card-novo',
        'oque': 'Informar a data, a região, as rotas e o código do operador do monitoramento, e criar o checklist.',
        'onde': 'Aba Devoluções → cartão "Novo checklist".',
        'porque': 'O checklist é a capa de papel digitalizada: a região e as rotas identificam a devolução para todos os setores.',
        'quando': 'Quando a capa chega da revenda.',
        'atencao': 'Placa, motorista e transportadora quem informa é a Portaria, no recebimento — você não precisa preencher.',
      },
      {
        'titulo': 'Lançar as linhas, inclusive duas parciais da mesma nota',
        'tab': 'devolucoes', 'destaque': '.dev-linha-nova',
        'cenario': 'devolucao_lancada',
        'oque': 'Preencher nota, parcial (com o número), cliente, caixas, produto, Nº DEV e motivo. Para outra parcial da mesma nota, usar o botão "mesma nota".',
        'onde': 'Aba Devoluções → checklist aberto → última linha da tabela.',
        'porque': 'Quando o cliente devolve duas caixas do mesmo produto por motivos diferentes, ele emite duas parciais na mesma nota. O número da parcial é o que amarra cada Nº DEV à caixa certa.',
        'quando': 'Ao lançar a capa, linha por linha.',
        'atencao': 'O código do cliente puxa sozinho o RCA e o supervisor do cadastro — e o que você lança ensina a base para a próxima vez.',
      },
      {
        'titulo': 'Lançar uma SOBRA',
        'tab': 'devolucoes', 'destaque': '#dev-card-sobra',
        'oque': 'Criar o checklist de sobra e lançar caixa, peso, produto e motivo.',
        'onde': 'Aba Devoluções → cartão "Lançar SOBRA".',
        'porque': 'Sobra não tem carga nem rota: ela só entra. O ciclo é curto — Portaria dá o OK, Faturamento dá o OK, Expedição dá o OK e acabou.',
        'quando': 'Quando o monitoramento passar a sobra.',
      },
      {
        'titulo': 'Gerar o relatório do dia e a relação para o operador',
        'tab': 'devolucoes', 'destaque': 'button[onclick^="relatorioOperadorDevolucoesUI"]',
        'oque': 'Gerar o "Relatório do dia" (conferência completa) ou a "Relação para o operador" (a lista para mandar).',
        'onde': 'Aba Devoluções → botões ao lado do filtro de dia. Também na aba Relatórios, com escolha de data.',
        'porque': 'São dois documentos diferentes de propósito: o relatório do dia mostra a conferência inteira; a relação para o operador leva só nota, parcial, supervisor, RCA, cliente, caixa, peso, produto, Nº DEV, data e motivo.',
        'quando': 'No fechamento, e sempre que o operador do monitoramento pedir.',
      },
      {
        'titulo': 'Manter os cadastros em dia',
        'tab': 'cadastros', 'destaque': '#tab-cadastros',
        'oque': 'Cadastrar produto (com o quilo da caixa), motivo, supervisor e cliente — e exportar qualquer relação em CSV.',
        'onde': 'Aba Cadastros.',
        'porque': 'Cadastro bom é o que faz o lançamento ser rápido: o produto sugere o peso, o cliente traz o RCA e o supervisor.',
        'quando': 'Sempre que aparecer um item novo.',
      },
    ],
  },

  'Administração': {
    'email': 'guia.adm@suinco.demo',
    'icone': '🛡️',
    'missao': 'Comandar o painel: usuários, cadastros, auditoria e relatórios.',
    'resumo': [
      'Você enxerga e faz tudo o que os outros setores fazem, e mais: cria usuários e restaura versões.',
      'Toda alteração relevante guarda o estado anterior — dá para ver quem mudou o quê e voltar atrás.',
      'É o posto que responde quando alguém pergunta "por que este número está assim".',
    ],
    'passos': [
      {
        'titulo': 'Entrar no painel',
        'tab': None, 'destaque': '#login-servidor',
        'oque': 'Entrar com o seu e-mail e a sua senha.',
        'onde': 'Tela de entrada.',
        'porque': 'O acesso de Administração é irrestrito — por isso ele é nominal.',
        'quando': 'Uma vez por turno.',
      },
      {
        'titulo': 'Criar e gerenciar os operadores',
        'tab': 'usuarios', 'destaque': '#tab-usuarios',
        'oque': 'Cadastrar cada pessoa com o setor dela.',
        'onde': 'Aba Usuários.',
        'porque': 'O setor decide o que a pessoa vê e o que ela pode escrever. É assim que a Portaria não mexe no que é do Faturamento.',
        'quando': 'Na entrada de cada novo colaborador.',
      },
      {
        'titulo': 'Acompanhar o dia inteiro pela Torre',
        'tab': 'torre', 'destaque': '#torre-stats, .stat-grid',
        'oque': 'Olhar as caixas do topo e clicar para filtrar.',
        'onde': 'Aba Torre de Controle.',
        'porque': 'É a visão de comando do pátio, sem precisar entrar em cada aba.',
        'quando': 'O tempo todo.',
      },
      {
        'titulo': 'Auditar e restaurar uma devolução',
        'tab': 'devolucoes', 'destaque': 'button[onclick^="abrirRevisoesDevolucaoUI"]',
        'cenario': 'devolucao_lancada',
        'oque': 'Abrir "Alterações" no checklist e, se precisar, restaurar uma versão anterior.',
        'onde': 'Aba Devoluções → checklist aberto → botão "Alterações".',
        'porque': 'Cada mudança guarda o estado anterior. Restaurar traz status e carimbos JUNTOS — o documento nunca fica dizendo duas coisas ao mesmo tempo.',
        'quando': 'Quando houver dúvida sobre uma alteração, ou um lançamento errado a desfazer.',
      },
      {
        'titulo': 'Gerar os relatórios',
        'tab': 'relatorios', 'destaque': '#tab-relatorios',
        'oque': 'Escolher o período e gerar Operacional, Executivo, Devoluções ou a Relação para o operador.',
        'onde': 'Aba Relatórios.',
        'porque': 'Os PDFs saem do servidor, iguais em qualquer aparelho, com o status atual.',
        'quando': 'No fechamento do dia e nas reuniões.',
      },
    ],
  },
}
